### PR TITLE
android: ignore volume keys

### PR DESCRIPTION
**Pull request by alula**
- [x] Tested on all platforms changed
- [ ] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Review by msiglreith — APPROVED** [review]
Thanks, fine for me

cc @MarijnS95 to check that you don't require it by chance

**Comment by MarijnS95** [comment]
I miss proper justification why this is disabled. The main problem appears to be that `winit` marks every key as "handled" regardless of what the application does with it.

What if someone built an audio application with Winit and listens for volume keys for some reason or another, and suddenly doesn't receive them anymore?

Besides, we're at 65 characters of indentation now, this is getting beyond maintainable.

**Comment by maroider** [comment]
> The main problem appears to be that winit marks every key as "handled" regardless of what the application does with it.

It seems like there's a need to expose the ability to set the "handled" state of certain events, and not just on Android (see #1768).

**Comment by torokati44** [comment]
> It seems like there's a need to expose the ability to set the "handled" state of certain events, and not just on Android

I definitely agree, but until that, as a stopgap, I'd love to see this merged!

**Pull request closed without merging**
