### PR TITLE
Remove `EventLoopError::AlreadyRunning`

### PR DESCRIPTION
**Pull request by madsmtm**
This is already prevented by the type-system, and as such it doesn't make sense to have an error case for this.

This was added by @rib in https://github.com/rust-windowing/winit/pull/2767, maybe you can shed some light on if this was an oversight added out of an abundance of caution, or if you think my reasoning is wrong here, and the error actually can happen?

- [ ] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]
From a quick view this makes sense. The `EventLoop` cannot be mutably borrowed more than once, and there's no way to `Copy`/`Clone` one to get multiple mutable references either.

**Review by kchibisov — APPROVED** [review]

**Comment by kchibisov** [comment]
I don't think that it's an issue actually? Like you can probably start with pump events for one iteration, but then continue with `run` or `run_on_demand`?

**Comment by kchibisov** [comment]
At least it should kind of work now.

**Comment by rib** [comment]
> Like you can probably start with pump events for one iteration, but then continue with run or run_on_demand?

Yeah I think it's just that you'd get ambiguous semantics to try and do something like that, e.g. considering that you probably won't get a `StartCause::Init` event.

Since it's a weird case, I think my preference at the time was to throw an error instead of having to think about what semantics to promise users.

**Pull request merged**
