### PR TITLE
wayland: dispatch pending events before NewEvents

### LINKED ISSUE #1148: Wayland dropping events when blocking in event loop
While trying to refactor the glutin update for Alacritty a bit, I've noticed an issue with the way the event loop operates when it is blocked.

On Wayland, when the window is frequently redrawn and the event loop is blocked for short periods of time, it's possible that key release events are dropped, leading to infinite `ReceiveChar` events.

I was able to reproduce this with this minimal examlpe in Sway:

```rust
mod support;

use glutin::event::{Event, WindowEvent};
use glutin::event_loop::{ControlFlow, EventLoop};
use glutin::window::WindowBuilder;
use glutin::ContextBuilder;

fn main() {
    let el = EventLoop::new();
    let wb = WindowBuilder::new().with_title("A fantastic window!");

    let windowed_context =
        ContextBuilder::new().build_windowed(wb, &el).unwrap();

    let windowed_context = unsafe { windowed_context.make_current().unwrap() };

    println!(
        "Pixel format of the window's GL context: {:?}",
        windowed_context.get_pixel_format()
    );

    let gl = support::load(&windowed_context.context());

    el.run(move |event, _, control_flow| {
        println!("{:?}", event);
        *control_flow = ControlFlow::Wait;

        match event {
            Event::LoopDestroyed => return,
            Event::WindowEvent { ref event, .. } => match event {
                WindowEvent::ReceivedCharacter(c) => {
                    std::thread::sleep_ms(10);
                    gl.draw_frame([1.0, 0.5, 0.7, 1.0]);
                    windowed_context.swap_buffers().unwrap();
                }
                WindowEvent::Resized(logical_size) => {
                    let dpi_factor =
                        windowed_context.window().hidpi_factor();
                    windowed_context
                        .resize(logical_size.to_physical(dpi_factor));
                }
                WindowEvent::RedrawRequested => {
                    std::thread::sleep_ms(10);
                    gl.draw_frame([1.0, 0.5, 0.7, 1.0]);
                    windowed_context.swap_buffers().unwrap();
                }
                WindowEvent::CloseRequested => {
                    *control_flow = ControlFlow::Exit
                }
                _ => (),
            },
            _ => (),
        }
    });
}
```

Pinging @vberger since I've already mentioned this on #glutin and this might be relevant to one of the Wayland libraries.

According to @kchibisov, the `sleep_ms(10)` might not be enough depending on the system, he's had to change it to `30` for example. High key repeat rates are also necessary, the `30` ms were with a repeat rate of `60` and my tests were done with the maximum Sway repeat rate (I've just set it to `600`). Even then a reproduction is a bit spurious, though very reliable in my case (I can reproduce in at least 90% of attempts).

### PR DESCRIPTION
**Pull request by vberger**
When we are woken up from calloop(mio) wait, always attempt to
dispatch pending events even though calloop should have done it.

When using OpenGL, mesa shares our wayland socket, and also reads
from it, especially if vsync is enabled as it'll do blocking reads.
When doing so, it may enqueue events in the internal buffer of our
event queue.

As the socket has been read, mio will thus not notify it to calloop
as readable, and thus calloop will not know it needs to dispatch. In some
cases this can lead to some events being delivered much later than
they should. Combined with key repetition this can actually cause some
flooding of the event queue making this effect event worse.

Fixes #1148

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by vberger** [comment]
Let it be know that this is the result of 5 epic hours of println-debugging and at least 20 recompilations of alacritty. :fire:

**Comment by kchibisov** [comment]
I've mentioned one bug with this PR I'm observing in alacritty in #smithay , so probably needs some investigation.

Just for the reference, with this patch applied alacritty can freeze during resize/startup, so looks like

Screenshot_Mon 09 Sep 2019 01:58:39 AM MSK

The left instance is dead, so can't resize/kill with wm hotkey.

backtrace:
[backtrace.txt](https://github.com/rust-windowing/winit/files/3588592/backtrace.txt)

**Comment by vberger** [comment]
Yes, can reproduce. I think I have a guess about what happens, looks like the patch will have to be more subtle.

**Comment by vberger** [comment]
New version of the patch, which is less brutal in its approach to dispatching and should not get stuck any more.

My few attempts with alacritty locally seems to indicate that this does indeed solve it, can you confirm @kchibisov ?

**Comment by kchibisov** [comment]
Seems like I can't repro anymore, was spamming terminals with repeat_rate 255 and instantly closing them, fullscreening, resizing and so on. Nice!

**Comment by Osspial** [comment]
@vberger Hey, it doesn't look like this ever got a changelog entry. Could you add that in?

**Comment by vberger** [comment]
Ah sorry about that, will do.

**Pull request merged**
