### PR TITLE
chore(changelog): write migrations for 0.30

### PR DESCRIPTION
**Pull request by kchibisov**
Add a migrations for the big API changes showcasing how to upgrade some common snippets of old code to new APIs.

Blocked on https://github.com/rust-windowing/winit/pull/3590.

### CODE REVIEW

**Comment by kchibisov** [comment]
TODO: Add a link why certain thing was changed.

**Review by daxpedda — COMMENTED** [review]
I think I would prefer sticking to #3612.

**Comment by kchibisov** [comment]
we've discussed that with @madsmtm and my only issue with his patch was that it was too long and more informal. Things already happened, so you should say how to do and be more incremental. Anyway, do with this PR whatever you both want.

**Comment by madsmtm** [comment]
I incorporated some of my ideas from https://github.com/rust-windowing/winit/pull/3612 into this one, and opened https://github.com/rust-windowing/winit/issues/3626 as the place to submit feedback.

**Review by madsmtm — APPROVED** [review]

**Review by daxpedda — APPROVED** [review]

**Pull request merged**
