### PR TITLE
On Wayland, drop wl_surface on window close

### PR DESCRIPTION
**Pull request by kchibisov**
- [x] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

r @mahkoh

### CODE REVIEW

**Comment by mahkoh** [comment]
You could do this without unsafe by having a `SurfaceHolder` stored in WindowHandle after `window`. `SurfaceHolder` would then destroy the surface when dropped. Your code seems correct.

**Comment by kchibisov** [comment]
@mahkoh I do like it with unsafe, since I'm being certain that way in which order rust will drop stuff, in fact that's what's ManuallyDrop was meant for. If I store after window I wouldn't be that certain.

**Comment by mahkoh** [comment]
You could be certain because struct is specified to drop fields from top to bottom. Anyway, the current version is fine by me.

**Comment by kchibisov** [comment]
>You could be certain because struct is specified to drop fields from top to bottom. Anyway, the current version is fine by me.

Yeah, but then some other folks who'll take a look at the code should be aware that ordering isn't changed, that way it's more clear. Though, it's a matter of opinion.

**Pull request merged**
