### PR TITLE
Android

### PR DESCRIPTION
**Pull request by j4qfrost**
- [ ] Tested on all platforms changed
- [ ] Compilation warnings were addressed
- [ ] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by j4qfrost** [comment]
@dvc94ch committed the suggested changes

**Comment by dvc94ch** [comment]
This pr would need to be rebased and the android work completed. There are still issues with orientation changes. The deviceid change should be a separate PR as it's unrelated. Also the changes are not complete, you'd have to add the method to all backends.

**Comment by goddessfreya** [comment]
I'm confused as to why a Android PR is touching files in `src/platform_impl/linux/**`.

**Comment by dvc94ch** [comment]
Closing in favor of #1556

**Pull request closed without merging**
