### PR TITLE
Fix window resize cursor orientation on X11 and Wayland

### LINKED ISSUE #1912: Window corner resize cursor has the wrong orientation
This is an issue that appeared in [egui](https://github.com/emilk/egui/). But we suspect that it might be an issue with winit.

Original report (https://github.com/emilk/egui/issues/332):

**Describe the bug**
When I place the cursor in any corner of a window that can be resized, it points in the wrong direction.

image

**Expected behavior**
image

**System information**
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.11.14-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11

### PR DESCRIPTION
**Pull request by EmbersArc**
Fixes #1912 

- [x] Tested on all platforms changed ~~Looking for someone to test it on Wayland~~ confirmed issue on Wayland as well (https://github.com/rust-windowing/winit/issues/1912#issuecomment-860279865) 
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Review by maroider — APPROVED** [review]
Can you check if this PR gives the desired result for you, @akhilman.

**Comment by akhilman** [comment]
> Can you check if this PR gives the desired result for you, @akhilman.

Arrow orientation is good with this PR.

**Comment by mankinskin** [comment]
Can this be merged?

**Comment by maroider** [comment]
cc @kchibisov

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
