### PR TITLE
Write migration instructions for `v0.30`

### LINKED ISSUE #3477: Write migrations for each release
We should write migrations between releases showing who to port certain code and probably linking to discussions why certain change were made in the first.

Then e.g. rustdoc/CHANGELOG could link to relevant entries for migrations.

An example for such migration is like that: 

https://github.com/rust-windowing/winit/pull/3447#discussion_r1484396211

The migrations should probably in `migrations` directory with format `migration_release.md`(only for major releases with breaking changes).

### PR DESCRIPTION
**Pull request by madsmtm**
Fixes #3477.

I've not yet finished the issue description for the feedback issue, my WIP on that is below, will update this description later.

```md
# Feedback on migration to trait-based design

We're interested in [...]

See https://github.com/rust-windowing/winit/issues/3432 for more details.
```

### CODE REVIEW

**Comment by kchibisov** [comment]
I was actually doing the same based on my PR which made the sections, you can look into how it was done 

https://github.com/rust-windowing/winit/pull/3614

**Review by daxpedda — COMMENTED** [review]
I think I would prefer more sub-headers and separating the migration from the regular changelog entries but still keep it in the same file.

**Comment by kchibisov** [comment]
ping @madsmtm @daxpedda with the context of https://github.com/rust-windowing/winit/pull/3614

I can finish myself, since anything that is not overly verbose/informal is fine.

**Comment by madsmtm** [comment]
I've merged this into https://github.com/rust-windowing/winit/pull/3614.

**Pull request closed without merging**
