### PR TITLE
Process WM_SYSCOMMAND to forbid screen savers in fullscreen mode

### LINKED ISSUE #1047: Process WM_SYSCOMMAND to forbid screen savers in fullscreen mode

### PR DESCRIPTION
**Pull request by dam4rus**
Fixes #1047

Tested only on Windows 10, but should work on previous version.

- [ ] Tested on all platforms changed
- [x] `cargo fmt` has been run on this branch
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by Osspial** [comment]
Thanks for implementing this!

These changes look good. All it needs is a changelog entry, and I'll merge it.

**Comment by dam4rus** [comment]
No problem at all!

Where should i put this behavior in the documentation?

**Comment by ZeGentzy** [comment]
@dam4rus I'd put it here: https://docs.rs/winit/0.20.0-alpha2/winit/window/struct.WindowBuilder.html#method.with_fullscreen

I'd change [this function's doc](https://docs.rs/winit/0.20.0-alpha2/winit/window/struct.Window.html#method.set_fullscreen) to link to `with_fullscreen`'s doc.

**Comment by ZeGentzy** [comment]
Yes, and now I'd link the two docs like this: https://doc.rust-lang.org/src/alloc/vec.rs.html#284

**Comment by dam4rus** [comment]
@ZeGentzy I've updated the documentation for https://docs.rs/winit/0.20.0-alpha2/winit/window/struct.WindowBuilder.html#method.with_fullscreen, but shouldn't we link all documentation from https://docs.rs/winit/0.20.0-alpha2/winit/window/struct.Window.html to it's WindowBuilder counterpart then? I think it would be weird if only this function is a link to another documentation.

**Comment by dam4rus** [comment]
I've opened an issue for the docs change

**Comment by ZeGentzy** [comment]
Hey @Osspial, I can't merge this 'cause rustfmt is failing. :(

**Comment by ZeGentzy** [comment]
Can you rebase this against master, so that the CI fixes it self?

**Pull request merged**
