### PR TITLE
X11: Fix events not being reported promptly

### PR DESCRIPTION
**Pull request by murarth**
- [x] Tested on all platforms changed
- [x] `cargo fmt` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by murarth** [comment]
I believe this should fix both rust-windowing/glutin#1054 and rust-windowing/glutin#1193

**Comment by ZeGentzy** [comment]
cc @chrisduerr

**Comment by JohnDoneth** [comment]
Thanks for all your work on this! I just tested it and can confirm that it fixed the issues I was having in rust-windowing/glutin#1193

**Comment by Osspial** [comment]
Can we get a changelog entry before merging this?

**Comment by murarth** [comment]
Added an entry to the changelog and rebased to resolve the conflict.

**Pull request merged**
