### PR TITLE
X11: Fix panic when no monitors are available

### PR DESCRIPTION
**Pull request by murarth**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by murarth** [comment]
Fixes #705 by returning a dummy `MonitorHandle` when no monitors are available. This seemed like the most straightforward fix, as the platform-independent facade would not permit returning an `Option<MonitorHandle>` from `Window::current_monitor`. The dummy `MonitorHandle` has an `id` value of `0` (an invalid `XID` value) and a few checks are added to avoid caching this dummy handle or using it as though it were valid.

I was unable to reproduce the original issue myself, so I hope that someone still experiencing the issue will test this and let me know if any new bugs occur as a result of this change.

**Comment by vberger** [comment]
Overall, what would happen if a user unknowingly tries to use this dummy monitor handle as it were the main monitor for their app, by passing it to `set_fullscreen`, or by calling the methods of `MonitorHandle` to get its name / position / dpi factor?

**Comment by murarth** [comment]
Replaced a `return Err` with a default DPI factor of 1.0 to avoid another panic. This should address #1007.

**Comment by ZeGentzy** [comment]
Should be good to merge when CI is done?

**Comment by murarth** [comment]
@ZeGentzy Yes, I think so.

**Pull request merged**
