### PR TITLE
Initial Xbox Gamepad support

### PR DESCRIPTION
**Pull request by HeavyRain266**
Initial change for #2506 which in the future hopefuly will introduce Xbox platform based on Win32/WinRT APIs which are not under NDA.

> **Note** [`Windows.Gaming.Input`](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input?view=winrt-22621) API depends on focused window and [`Gamepad`](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad?view=winrt-22621) module provides Xbox specific metadata such as assigned users, which is required for upstream console compatibility.

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by HeavyRain266** [comment]
@msiglreith Could you help me model this feature as windows specific to not interact with other platforms?

(I've been told on matrix to ping you here)

**Comment by msiglreith** [comment]
Have you looked into the old gamepad PR already? https://github.com/rust-windowing/winit/pull/1969
In general it would be nice to keep the user facing API similar if possible but I haven't looked into the new gaming API at all so far besides the comments in the issue

**Comment by HeavyRain266** [comment]
> Have you looked into the old gamepad PR already? https://github.com/rust-windowing/winit/pull/1969
> In general it would be nice to keep the user facing API similar if possible but I haven't looked into the new gaming API at all so far besides the comments in the issue

I have not but someone linked old branch with implementation based on HID instead, thanks for porting this one out.

New API is a bit different from Xinput as of being rewritten in C++ with more support for more kinds of gaming input than gamepads and requipment for focused window. Users are mostly using gilrs instead which doesn't require any changes in winit itself for cross platform gamepad handling. There is some info about [migration](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/input/porting/input-porting-xinput), could be mapped 1:1 with previous PR but also add API features required for xbox compatibility on top.

**Comment by HeavyRain266** [comment]
Unfortunatelly, I'm closing this for now, as I have no time to rebase it and then start testing the new API. I will get back to it in coming months as it requires deeper knowledge of winit internals and a lot of planning and testing.

**Pull request closed without merging**
