### PR TITLE
add android NDK event loop

### LINKED ISSUE #721: HiDPI not fully supported on Android
On Android, `get_hidpi_factor` currently always returns `1.0`. According to @francesca64 this is blocked on tomaka/android-rs-glue#116.

### LINKED ISSUE #789: Determining visible area on Android
The dimensions of visible area on android (and maybe on iOS too) differs from entire window size. It because the status bar (and sometimes soft keyboard) partially overlaps it. So it should provide method to determine actual visible area.

As I found, the one of way to determine that area looks like:

```java
Rect rect = new Rect();
window.getDecorView().getWindowVisibleDisplayFrame(rect);
```

The `rect.top` usually equals to the height of status bar (when it shown of course).
The `rect.bottom` equals to the height of window, but sometimes when software keyboard is used it less than window height by self height of keyboard.

I'm not an Android apps developer, so I may mistakes.

As I understand the methods `Window::get_inner_size()` and `Window::get_inner_position()` cannot be fixed to return the actually visible area because it related to drawing context, but visible area related to viewport (in GL terms).

I suppose introduce additional methods like a:
```
fn get_view_position(&self) -> Option<LogicalPosition>;
fn get_view_size(&self) -> Option<LogicalSize>;
```

The first returns `(rect.left, rect.top)`, the second returns `(rect.right - rect.left, rect.bottom - rect.top)`.

### LINKED ISSUE #948: EventLoop 2.0 for Android
This issue tracks the implementation of the EventLoop 2.0 rework on Android.

**Winit does not currently have any contributors able to implement this. If you are interested in Winit functioning on Android, please consider implementing this.**

### PR DESCRIPTION
**Pull request by JasperDeSutter**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

These are not my changes, this backports the work (https://github.com/goddessfreya/winit/pull/2) of @dvc94ch to winit master. I have no issue if they want to take over this PR.

Running an example on an android device needs a couple things, add this to Cargo.toml:
```toml
[[example]]
name = "request_redraw_threaded"
crate-type = ["cdylib"]
```

And add this to the example file:
```rust
#[cfg(target_os = "android")]
ndk_glue::ndk_glue!(main);
```

Now start the application with `cargo apk run --example request_redraw_threaded`

Closes #721, closes #789, closes #948 cc @katyo

### CODE REVIEW

**Comment by dvc94ch** [comment]
Great work thanks!

**Comment by dvc94ch** [comment]
@JasperDeSutter can you add the ci changes to this PR too?

**Comment by dvc94ch** [comment]
@JasperDeSutter it's on my todo list to merge before end of the week, let's just give it a couple more days incase someone wants to comment.

**Comment by JasperDeSutter** [comment]
Okay, sounds great!

**Comment by dvc94ch** [comment]
Needs rebasing.

I'm wondering if it makes sense to add the ndk glue to all examples.
```rust
#[cfg(target_os = "android")]
ndk_glue::ndk_glue!(main);
```

The other issue is that android apps rely on `Suspend` and `Resume` events being emitted. So a winit application that wasn't written with android in mind won't work. But if all backends emit `Suspend` and `Resume` events a winit application written for android can work on all platforms.

**Pull request merged**
