### PR TITLE
Properly remove window mouse event listeners

### PR DESCRIPTION
**Pull request by DouglasDwyer**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] [N/A] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] [N/A] Created or updated an example program if it would help users understand this functionality
- [ ] [N/A] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

The web backend for `winit` registers the `onmousedown`, `onmouseup`, and `onmousemove` events on the global Javascript window object. When the `winit` window is destroyed, however, these events are not properly removed. This is because the events are registered with the `capture: true`, but `capture: true` is not passed to the appropriate `removeEventListener` call. This PR updates the web backend to pass the event creation options to the event removal function. This prevents errors in which the Javascript runtime tries to invoke the event listener closures after they are destroyed.

### CODE REVIEW

**Comment by maroider** [comment]
It looks like you're right about that, but I'm stumped as to how you managed to observe it in the first place.

**Comment by DouglasDwyer** [comment]
@maroider Absolutely! This can be reproduced by creating a Winit window on the web platform, and then dropping it, while allowing the event loop to continue. When you wave your cursor over the browser window after this happens, errors about a destroyed closure should appear in the console.

**Review by madsmtm — APPROVED** [review]
I'm fine with merging this now unless @maroider wants to test it first?

**Comment by maroider** [comment]
I had a go at following your instructions, but I couldn't get the error to show up in the console. It's probably fine to merge it as-is, even if I couldn't reproduce the issue, as the MDN docs clearly show we're using `removeEventListener` wrong anyway.

**Comment by madsmtm** [comment]
Thank you @DouglasDwyer!

**Pull request merged**
