### PR TITLE
Fix panic upon closing the app on iOS

### PR DESCRIPTION
**Pull request by aleksijuvani**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by aleksijuvani** [comment]
r? @mtak- 
I'm not sure if this should be waiting for both `ProcessingEvents` and `ProcessingRedraws`. For me this was only ever called with `ProcessingEvents`, but I'm not using a directly Metal-backed view (instead it's a sublayer), so perhaps I'm triggering a different code path than your application.

**Comment by Osspial** [comment]
Is this good to merge? cc @mtak- again

**Comment by Osspial** [comment]
Are there any example Winit Metal applications this could be tested with?

**Comment by aleksijuvani** [comment]
It looks like glutin is creating a directly GL-backed view for the window, so this can be tested with the glutin examples. The changes here look correct. The panic can be reproduced with these examples, and the issue is fixed after applying the changes in this pull request.

**Pull request merged**
