### PR TITLE
Only build, but don't run tests in MSRV CI

### PR DESCRIPTION
**Pull request by madsmtm**
Since the MSRV of development dependencies can easily be bumped without it affecting the MSRV of the published version of `winit`.

Done because the `image` crate now has an MSRV of 1.61: https://github.com/image-rs/image/commit/11492233cd59fc0e2701ab12cd00607e9bbf125c

### CODE REVIEW

**Comment by msiglreith** [comment]
Is it possible to define th MSRV in an `env` section within the github workflow, so it can be referenced? Having to sync multiple locations on an update doesn't seem good to me

**Comment by madsmtm** [comment]
> Is it possible to define th MSRV in an `env` section within the github workflow, so it can be referenced? Having to sync multiple locations on an update doesn't seem good to me

I found a way without using `env`, though I don't think that's really ideal though.

I'm unsure if `env` works inside the `strategy` key, but I guess I should just try it.

**Comment by maroider** [comment]
We could get the number of explicit mentions of the MSRV down to zero if we'd like, but the way I'd propose to do that is a bit hacky.

Basically, we'd define a step that reads the MSRV from our CARGO.toml, and then makes that available to subsequent steps through `steps.rust-version.outputs.version`.
```yaml
    - id: rust-version
      run: bash -c "echo version=\$(grep rust-version Cargo.toml | grep -P -o \"\d*\.\d*.\d*\")" >> $GITHUB_OUTPUT
```

**Comment by madsmtm** [comment]
Given that we also write our MSRV in READMEs and such elsewhere, I don't think it's worth it. When one wants to do an MSRV bump, all one has to do is grep for the current MSRV

**Comment by kchibisov** [comment]
I don't like the use of `MSRV`. Could we just explicitly use the version? It doesn't save us anything and I like explicit version, since I can `grep` the version and automatically `sed` it.

Besides that the change sounds good to me.

**Comment by madsmtm** [comment]
I agree with @kchibisov that just duplicating the version is fine, given that it's done so all over our documentation as well

**Comment by madsmtm** [comment]
I'll just go with this as it is now, since the failing CI is blocking everything else, feel free to open a new PR if you want to move the MSRV to only be specified in one place

**Pull request merged**
