### PR TITLE
Fix incorrect changelog entry for #1524

### PR DESCRIPTION
**Pull request by maroider**
Don't know how this one slipped through, but it caused some confusion on the Rust gamedev discord.

---
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by ArturKovacs** [comment]
There's also this entry under v0.22.1
> - On Windows, drag and drop can now be disabled with `WindowBuilderExtWindows::with_drag_and_drop(false)`.

But `with_drag_and_drop` doesn't exist in the repo at the tag `v0.22.1`, so we should remove that as well while we are at it. (I'm assuming this got tangled during a merge or similar)

**Comment by maroider** [comment]
> I'm assuming this got tangled during a merge or similar

It seems like GitHub's code review interface [may be at fault](https://github.com/rust-windowing/winit/pull/1524/commits/6c105d1d08c8f625ad33a63b13288cba0f7027c5), but difficult to be certain (there was already a changelog entry in the correct place before the linked commit).

---

I'm a bit annoyed that CI is required to run successfully despite CHANGELOG.md being excluded from triggering CI runs, so I feel like it may be worth looking into doing something about that.

**Comment by ArturKovacs** [comment]
> I'm a bit annoyed that CI is required to run successfully despite CHANGELOG.md being excluded from triggering CI runs

Oh no, you are right, this currently prevents this PR from getting merged. As far as I know, I'm not authorized to change such things so my recommendation is to add an empty line in a rust file of your liking 😀. (Or an empty comment line if the empty line is removed by `cargo fmt`)

**Comment by maroider** [comment]
@francesca64, you have administrative privileges, so you can merge this, right?

**Pull request merged**
