### PR TITLE
add composition event support for Mac

### PR DESCRIPTION
**Pull request by kaiwk**
- [ ] Tested on all platforms changed
   - [x] Tested on Mac
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

see: #1497

### CODE REVIEW

**Comment by kchibisov** [comment]
I'll take a look on it once we figure out renaming and preferred event structure on #1622, if you have any concerns or questions you can chime in.

**Comment by kchibisov** [comment]
We've updated the composition branch, so if you can update your PR based on that it'll be nice.

**Comment by kchibisov** [comment]
Note, you'd need to send IME::Enable at some point, though, given that both X11 and macOS doesn't have such information I may end up removing this even entirely.

**Comment by kaiwk** [comment]
Not sure why CI failed.

**Pull request closed without merging**
