### PR TITLE
[DRAFT] Move error and dpi types into a separate crate + split out x11 symbol loading code + xinerama & multihead support

### PR DESCRIPTION
**Pull request by goddessfreya**
See https://github.com/rust-windowing/winit_types and https://github.com/rust-windowing/glutin_x11_sym.

@murarth @Osspial Are you folks familiar with how to setup CI for glutin_x11_sym, glutin_sys and winit_types?

Platforms:
- [x] X11
- [x] Wayland
- [x] Macos
- [x] Windows
- [x] iOS
- [x] Web

Other: 
- [ ] Tested on all platforms changed
- [ ] Compilation warnings were addressed
- [ ] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by goddessfreya** [comment]
Hey @simlay, can you implement this for iOS? I couldn't get `cargo check` to work for iOS as it needed some SDK (which is of course linux only :/). Thanks :heart:

**Comment by simlay** [comment]
@goddesfreya sure! I’ll give it a whack!

**Comment by vbogaevsky** [comment]
Weren't we going to merge `dpi_overhaul` first?

**Comment by goddessfreya** [comment]
@vbogaevsky I don't think it particularly matters which order they land, does it? These changes don't really touch anything dpi related.

**Comment by Osspial** [comment]
@goddessfreya The DPI overhaul branch adds generics to the size and position types, and it'll be easier to manage this change if we delay merging this until after the generics have landed on master.

**Comment by daxpedda** [comment]
This is very old and needs to be remade completely.

Continues to be tracked in https://github.com/rust-windowing/winit/issues/2759.

**Pull request closed without merging**
