### PR TITLE
Stop emitting corporate characters in macOS

### LINKED ISSUE #778: Redundant ReceivedCharacter after arrow key and F key on macOS
When you enter the arrow keys and F keys on a Mac, there will be redundant ReceivedCharacter events compared to Linux and Windows.

For example, you can start the window with `cargo run --example window` on the Mac, and press Left Arrow key, you will see the redundant ReceivedCharacter event, which does not happen on Linux and Windows.

Here are some logs.
```
WindowEvent { window_id: WindowId(Id(140334732557360)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 124, state: Pressed, virtual_keycode: Some(Right), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(Id(140334732557360)), event: ReceivedCharacter('\u{f703}') }
WindowEvent { window_id: WindowId(Id(140334732557360)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 124, state: Released, virtual_keycode: Some(Right), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

### PR DESCRIPTION
**Pull request by hecrj**
Fixes #778.

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by hecrj** [comment]
@clarkmoody I am not sure of the consequences, but that would be simpler. I have implemented it here: https://github.com/hecrj/winit/commit/9dcb890482c518efc1dacba868885c78036b8284

If we decide to go for that approach, I can rebase this PR as needed.

**Comment by goddessfreya** [comment]
Hello @jdm, you appear to be on the testers list for MacOS! Lucky you! 

Want to give this PR a small test drive and make sure nothing's up? Thanks!

**Comment by vbogaevsky** [comment]
@hecrj could you update `CHANGELOG.md`, please?

**Comment by daxpedda** [comment]
> Good find!
> 
> Would it make sense to filter the entire [Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas)?

I think letting winit remove all private use area unicode characters would be a mistake. I stumbled lately on this while implementing a font for a conlanguage, that had a large amout of letters.

The private use area was specifically designed for use cases like this: http://www.unicode.org/faq/private_use.html.

> For example, they might be part of a constructed artificial script (ConScript) which has no general community of use.

> ... a particular implementation may need to use private-use characters for specific internal purposes.

That said, I think macOS corporate characters would make a good exception.

**Comment by hecrj** [comment]
@vbogaevsky Done!

**Pull request merged**
