### PR TITLE
Rename `new_user_event` to `with_user_event`

### PR DESCRIPTION
**Pull request by briankabiro**
Finishes #1057

- [ ] Tested on all platforms changed
- [x] `cargo fmt` has been run on this branch
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/winit/issues/1057#issuecomment-514384114

**Comment by briankabiro** [comment]
I think I had misinterpreted the comment but updated the method name correctly now.

**Comment by Osspial** [comment]
Thanks for implementing this! All we need is a changelog entry and this should be good to merge.

**Comment by briankabiro** [comment]
All done updating the CHANGELOG.

**Comment by ZeGentzy** [comment]
Can you try re-pushing? Appveyor seams angry.

**Comment by briankabiro** [comment]
Looks better now. 😃

**Pull request merged**
