### PR TITLE
X11: Fix misreporting DPI factor at startup

### LINKED ISSUE #998: EventLoop 2.0 misreporting DPI Factor at startup on X11
While looking at some remaining bugs in the EventLoop 2 version of Alacritty, I've noticed that the DPI Factor is always `1` at startup, regardless of which monitor the window is spawned on.

If the monitor is moved between monitors, the DPI is always updated correctly. So starting on a monitor with a 2.0 DPI and moving it to a different monitor and back will 'fix' the incorrectly reported DPI.

### PR DESCRIPTION
**Pull request by murarth**
Fixes #998

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by chrisduerr** [comment]
Can confirm that this fixes the issue for me.

**Comment by chrisduerr** [comment]
> While this PR didn't change master's behavior (or at least as far as I can tell), I can't confidently say it works.

I can. I'm not sure how your xrandr setup affects things though, since for me my monitors just have different DPI by default.

When starting on my primary monitor with 1.16666666666666667 DPI, I always get 1.0 reported from winit at startup. This PR fixes that.

**Comment by murarth** [comment]
@goddessfreya There are some necessary steps to reproducing the issue that may be missing from your test case:

* Build a window with `.with_visible(false)`
* Call `window.set_visible(true)` immediately after building (before entering `EventLoop::run`)
* Call `window.current_monitor()` (again, before entering the event loop)

On master, in this scenario, `window.current_monitor()` will return the monitor at `0, 0`, while, internally, winit will guess the window's DPI based on the monitor that currently contains the mouse pointer. If these are two different monitors with two different DPI factors, then the application will have received the wrong DPI factor (through the `current_monitor()` handle). Additionally, winit will not correct this by issuing a `HiDpiFactorChanged` event, if its internal guess had been accurate.

This PR fixes that inconsistency by assigning a window's `current_monitor` to the monitor that is guessed based on mouse pointer position. If this guess proves accurate, the application will have received the correct DPI factor. If the guess is not accurate (i.e. winit receives a `ConfigureNotify` event placing the window on a monitor other than the one guessed), winit will issue a `HiDpiFactorChanged` event to correct it, ultimately resulting in the application receiving the correct DPI factor.

I hope this makes clear exactly what this PR is aiming to fix.

**Comment by chutz** [comment]
I can confirm that this fixes https://github.com/jwilm/alacritty/issues/2938 for me

**Pull request merged**
