### PR TITLE
Webmerge3

### PR DESCRIPTION
**Pull request by ZeGentzy**
- [ ] Tested on all platforms changed
- [ ] `cargo fmt` has been run on this branch
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by Osspial** [comment]
Hold up, did we get approval from the parties involved to merge this ourselves? I didn't get any notifications about GitHub discussion on this. cc @hecrj @blm768 @ryanisaacg 

Generally speaking, I'm not comfortable having people submit PRs on other people's behalf, since that fucks up the git attributions.

**Comment by ZeGentzy** [comment]
@Osspial This was done with @ryanisaacg's approval. We discussed this on Discord. Apologies for not cluing you in.

**Comment by Osspial** [comment]
@ZeGentzy Discussing things off of GitHub is fine, it's just that this was a big merge done rather suddenly. I'm okay with doing this, but I'd at least like to have each author's work squashed separately, so that it's clear who did what when going through the git history.

**Comment by ZeGentzy** [comment]
@Osspial Squashing changes by author will take millennia, and each author's contributions probably will not compile without the final merge. I'd rather we either squash them all, or not squash them at all.

**Comment by Osspial** [comment]
@ZeGentzy could you re-push your `webmerge3` branch? I can see if there's a way to squash per-author easily.

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/winit/pull/1038

**Comment by felixrabe** [comment]
Re squashing: Please don't. Or at least keep the original commits around in a "web-orig" branch that is identical to the squashed version.

**Comment by Osspial** [comment]
I've enabled non-squashing merges, which preserves the author history.

**Comment by blm768** [comment]
FWIW, my changes have probably been largely overwritten in the process of @hecrj's refactoring, so I'm not sure it's worth making too much effort to preserve those particular changes' history. I'm not terribly worried about attribution; I'm just excited that I'll finally get to use `winit` on the Web.

**Comment by Osspial** [comment]
@blm768 I can get not being too worried about attribution from a user's perspective, but doing it wrong is something we could get in trouble for and has the potential to blow up into a debacle so I'm keen on doing it right if at all possible.

**Pull request merged**
