### PR TITLE
Relase alpha 6

### PR DESCRIPTION
**Pull request by Osspial**

### CODE REVIEW

**Comment by goddessfreya** [comment]
As discussed on discord, hoping #1335 lands before the release.

**Comment by chrisduerr** [comment]
Unless it holds it back forever, https://github.com/rust-windowing/winit/pull/1344 might also be interesting. That way the feature could be documented and "released" for desktop platforms (which is likely enough for most people) and existing users like Alacritty might benefit from the bugfixes?

The PR itself doesn't seem too controversial, so it might be worthwhile to consider.

**Comment by Osspial** [comment]
@chrisduerr That's a good call. I'll update that PR with the proper documentation.

**Comment by Osspial** [comment]
Closing in favor of #1352.

**Comment by kchibisov** [comment]
I am wondering whether it's a good idea to have some kind of stable winit version before `dpi-overhaul` gets merged, since dpi-overhaul is a massive change and having some kind of stable starting point (alpha6) before testing it downstream(e.g. in alacritty) will be a good idea imho.

I'm saying this, because in alacritty we were going to make release right after alpha6 and stick to some kind of stable winit releases afterwards, but now we're likely cut a new version with winit's git (we really don't want to do that, since it breaks bisecting).

I'm not saying that winit should do whatever popular downstream is doing right now and help them. I'm saying that dpi-overhaul wasn't likely closely tested in downstream clients at all and updating to it should take some time (even merging it will take some time) and stall downstream users' releases...

**Comment by Osspial** [comment]
@kchibisov I'd be fine with releasing `alpha6` without the DPI overhaul so that you have a release to pin to. However, the DPI overhaul is a *major* usability improvement for Winit that's been widely requested and worked on for quite a long time, and I don't want it to bitrot on the backburner when it's ready for release.

**Comment by kchibisov** [comment]
>I'd be fine with releasing alpha6 without the DPI overhaul so that you have a release to pin to.

Thanks, this will help us a lot with our winit "handling" and we can finally move to official winit releases instead of git master and forked glutin.

**Comment by chrisduerr** [comment]
Just to clarify, I'm all for making improvements available as quickly as possible, but I'd assume it will still take some time until DPI overhaul is merged and fully working.

So since there are a lot of bugfixes since the last release already, which are known to work pretty well, I think it makes sense to get those out to the user as quickly as possible so DPI overhaul can then be tested and ironed out without any pressure.

**Pull request merged**
