### PR TITLE
On Windows, avoid panic in `video_modes()`

### PR DESCRIPTION
**Pull request by fornwall**
We are seeing a panic due to the `unwrap()` usage in `video_modes()` in crash reporting.

Haven't been able to reproduce it ourselves, but in general [GetMonitorInfoW](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow) can fail, so this changes [MonitorHandle::video_modes()](https://docs.rs/winit/latest/winit/monitor/struct.MonitorHandle.html#method.video_modes) to return a `Result`.

### CODE REVIEW

**Comment by fornwall** [comment]
> did your crash reports show what kind of error Windows is returning here?

This is the available information:
> panic: called `Result::unwrap()` on an `Err` value: Os { code: 1461, kind: Uncategorized, message: "Invalid monitor handle." }

**Comment by fornwall** [comment]
Should we move the `get_monitor_info()` call out of the loop?

**Comment by kchibisov** [comment]
Can't we write something like that 

```diff
diff --git a/src/platform_impl/windows/monitor.rs b/src/platform_impl/windows/monitor.rs
index f1313970..1548bc05 100644
--- a/src/platform_impl/windows/monitor.rs
+++ b/src/platform_impl/windows/monitor.rs
@@ -230,44 +230,45 @@ impl MonitorHandle {
         // EnumDisplaySettingsExW can return duplicate values (or some of the
         // fields are probably changing, but we aren't looking at those fields
         // anyway), so we're using a BTreeSet deduplicate
-        let mut modes = BTreeSet::new();
-        let mut i = 0;
+        let mut modes = BTreeSet::<RootVideoMode>::new();
+        let mod_map = |mode: RootVideoMode| mode.video_mode;
+
+        let monitor_info = match get_monitor_info(self.0) {
+            Ok(monitor_info) => monitor_info,
+            Err(error) => {
+                log::warn!("Error from get_monitor_info: {error}");
+                return modes.into_iter().map(mod_map);
+            }
+        };
+
+        let device_name = monitor_info.szDevice.as_ptr();
 
+        let mut i = 0;
         loop {
-            unsafe {
-                match get_monitor_info(self.0) {
-                    Ok(monitor_info) => {
-                        let device_name = monitor_info.szDevice.as_ptr();
-                        let mut mode: DEVMODEW = mem::zeroed();
-                        mode.dmSize = mem::size_of_val(&mode) as u16;
-                        if EnumDisplaySettingsExW(device_name, i, &mut mode, 0) == false.into() {
-                            break;
-                        }
-                        i += 1;
-
-                        const REQUIRED_FIELDS: u32 =
-                            DM_BITSPERPEL | DM_PELSWIDTH | DM_PELSHEIGHT | DM_DISPLAYFREQUENCY;
-                        assert!(has_flag(mode.dmFields, REQUIRED_FIELDS));
-
-                        // Use Ord impl of RootVideoMode
-                        modes.insert(RootVideoMode {
-                            video_mode: VideoMode {
-                                size: (mode.dmPelsWidth, mode.dmPelsHeight),
-                                bit_depth: mode.dmBitsPerPel as u16,
-                                refresh_rate_millihertz: mode.dmDisplayFrequency * 1000,
-                                monitor: self.clone(),
-                                native_video_mode: Box::new(mode),
-                            },
-                        });
-                    }
-                    Err(error) => {
-                        log::warn!("Error from get_monitor_info: {error}");
-                        break;
-                    }
-                }
+            let mut mode: DEVMODEW = unsafe { mem::zeroed() };
+            mode.dmSize = mem::size_of_val(&mode) as u16;
+            if unsafe { EnumDisplaySettingsExW(device_name, i, &mut mode, 0) } == false.into() {
+                break;
             }
+
+            const REQUIRED_FIELDS: u32 =
+                DM_BITSPERPEL | DM_PELSWIDTH | DM_PELSHEIGHT | DM_DISPLAYFREQUENCY;
+            assert!(has_flag(mode.dmFields, REQUIRED_FIELDS));
+
+            // Use Ord impl of RootVideoMode
+            modes.insert(RootVideoMode {
+                video_mode: VideoMode {
+                    size: (mode.dmPelsWidth, mode.dmPelsHeight),
+                    bit_depth: mode.dmBitsPerPel as u16,
+                    refresh_rate_millihertz: mode.dmDisplayFrequency * 1000,
+                    monitor: self.clone(),
+                    native_video_mode: Box::new(mode),
+                },
+            });
+
+            i += 1;
         }
 
-        modes.into_iter().map(|mode| mode.video_mode)
+        modes.into_iter().map(mod_map)
     }
 }

```

**Comment by fornwall** [comment]
> Can't we write something like that

@kchibisov Looks like a good improvement -have update the PR with that!

**Review by msiglreith — APPROVED** [review]

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
