### PR TITLE
Composition event on web

### PR DESCRIPTION
**Pull request by t18b219k**
- [ ] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
## current tested platform
* Firefox 96.0.2(windows)
* Firefox 96.0.2(ubuntu)
* MS edge 97.0(windows)
* Epiphany(Ubuntu 20.04)
* Firefox Nightly 98.0a1(Android 9) 
* Android WebView 97.04(Android 9)
### buggy platforms 
* Chrome on android 9 with Microsoft SwiftKey.

expected preferable behavior Firefox with MS Swiftkey
`
compositionstart:
compositionupdate: ん
compositionupdate: に
compositionupdate: にh
compositionupdate: にほ
compositionupdate: にほん
compositionupdate: にほんg
compositionupdate: にほんご
compositionupdate: にほんごん
compositionupdate: にほんごんy
compositionupdate: にほんごにゅ
compositionupdate: にほんごにゅう
compositionupdate: にほんごにゅうr
compositionupdate: にほんごにゅうry
compositionupdate: にほんごにゅうりょ
compositionupdate: にほんごにゅうりょk
compositionupdate: にほんごにゅうりょく
compositionupdate: 日本語入力
compositionend: 日本語入力
`

buggy behavior Chrome with MS Swiftkey
`
compositionstart:
compositionupdate:
compositionstart:
compositionupdate: ん
compositionend: ん
compositionstart:
compositionupdate: ん
compositionupdate: に
compositionend: に
compositionstart:
compositionupdate: にh
compositionupdate: にほ
compositionend: にほ
compositionstart:
compositionupdate: にほ
compositionupdate: にほん
compositionend: にほん
compositionstart:
compositionupdate: にほんg
compositionupdate: にほんご
compositionend: にほんご
compositionstart:
compositionupdate: にほんご
compositionupdate: にほんごん
compositionend: にほんごん
compositionstart:
compositionupdate: にほんごんy
compositionupdate: にほんごにゅ
compositionend: にほんごにゅ
compositionstart:
compositionupdate: にほんごにゅ
compositionupdate: にほんごにゅう
compositionend: にほんごにゅう
compositionstart:
compositionupdate: にほんごにゅうry
compositionupdate: にほんごにゅうりょ
compositionend: にほんごにゅうりょ
compositionstart:
compositionupdate: にほんごにゅうりょk
compositionupdate: にほんごにゅうりょく
compositionend: にほんごにゅうりょく
compositionstart:
compositionupdate: にほんごにゅうりょく
compositionupdate: nihongonyuuryoku
compositionend: nihongonyuuryoku
`

## How to test
Open [Web demo using egui](https://t18b219k.github.io/egui_canvas) and enter text to TextEdit. 
if you want to try it on mobile devices please read this QR code.
image

This PR also support mobile text input. 
I don't have macos/ios computer.please test it.

### CODE REVIEW

**Comment by t18b219k** [comment]
I fixed all bug that i could found.
please test my work.

**Comment by gfreezy** [comment]
when the input focus is lost, the input box is still visible. I'm on macos.

https://user-images.githubusercontent.com/510012/155938901-16c3f724-d0e0-49aa-8678-19daf6f4eb98.mov

**Comment by JeftavanderHorst** [comment]
I'm experiencing a problem with the web demo. This may or may not have to do with your changes, not sure.

Tested on:
Android 10 (Motorola One Action)
Firefox 97.2.0
Keyboard: Microsoft Swiftkey 7.9.8.9

Steps to reproduce:
1. Focus on input field
2. Type an ascii character such as `a`
3. Type a special character such as `%`

The normal character is duplicated before the special character is inputted:

Screenshot (Mar 3, 2022 13 54 19)

**Comment by t18b219k** [comment]
@JeftavanderHorst Sorry for late response.
I can't reproduce on  Android 9 ( Xperia XZ1 compact ) with Swiftkey 8.10.10.4 .
Firefox nightly 100 works well but Chrome 99 not works .
this is related to differences in event firing order  between Firefox and Chrome.
if we combined chrome and swiftkey cause disaster.
please test.

**Pull request closed without merging**
