### PR TITLE
Remove support for `stdweb`

### PR DESCRIPTION
**Pull request by maroider**
- [ ] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

We have now had two releases of Winit (`0.24` and `0.25`) with the `stdweb` backed marked as deprecated (see #1662 and #1712). Removing it now seems like a reasonable thing to do at this point.

There is still some documentation to update, but this is mostly what I'd imagine would be required to remove `stdweb` support from Winit.

I do have one thing I'd like to get some opinions on: Should there still be a `web-sys` feature, or should it be unconditionally built now? I don't think there are any viable active alternatives to `web-sys` at the moment, although I know [@kettle11](https://github.com/kettle11) is working on [something](https://github.com/kettle11/kwasm) vaguely in that direction.

I know you've stepped down from maintaining Winit, @ryanisaacg, but I'd appreciate it if you had any comments. Similarly, I'd also appreciate any comments from @alvinhochun.

cc @ArturKovacs @francesca64 @msiglreith, as you guys are the remaining maintainers

### CODE REVIEW

**Comment by alvinhochun** [comment]
I'm fine with removing `stdweb` support.

I'm not sure about leaving the feature flag in or not. It would be nice to be able to easily add support for another web binding crate in the future, but as long as there isn't an alternative now it may be more of a burden.

**Comment by ryanisaacg** [comment]
Personally, I think it's unlikely there will be a new binding crate incompatible with the web-sys interface; I'm not aware of any that exist, other than stdweb (which predates it, is unmaintained, and is generally inferior). My recommendation would be to jettison all of the feature flags, and have the web target specifically and only be compatible with web-sys.

This is also a breaking change either way, and should be marked as such.

(However, take this with a grain of salt. I bet on stdweb and was wrong; maybe this bet is wrong too?)

**Comment by msiglreith** [comment]
I'm fine as well, including removing the feature flags.
Regarding `wasm-binding`, maybe there will be needs for compatibility with similar libraries (building on top of web-sys) in the future, but it might be possible to get rid of the dependency as well I guess.

**Comment by ArturKovacs** [comment]
I think a sufficient number of experts have spoken and I don't have a horse in this race, so I'd say let's move on with this, and also remove the `web-sys` feature flag in addition to the `stdweb` one.

**Comment by francesca64** [comment]
I also agree with what's been said.

**Comment by zicklag** [comment]
Sounds good to me. :+1:

**Comment by ArturKovacs** [comment]
@zicklag 😄 that's exactly the kind of energy we need here.

**Comment by maroider** [comment]
CI seems to be mostly happy now, and I think I've made all the required changes to documentation and the like. I'd like to run a sanity-check with a real program later, but this PR should otherwise be ready to be merged.

**Review by madsmtm — APPROVED** [review]

**Review by ArturKovacs — APPROVED** [review]

**Review by dsluijk — APPROVED** [review]

**Comment by ArturKovacs** [comment]
I'd say this can be merged, but I think @francesca64 only you wield the power to do so.

**Comment by msiglreith** [comment]
It looks like there are some outdated checks leftover in the branch settings which block the merge process:
grafik

**Comment by msiglreith** [comment]
@francesca64 Could you look at the checks above by chance? I assume it requires some changes in the admin settings.

**Comment by ArturKovacs** [comment]
I guess I should have written this earlier, but note that this was also brought up here https://github.com/rust-windowing/winit/pull/1952#issuecomment-850223936

**Pull request merged**
