### PR TITLE
Implement DPI Usability Upgrades for X11 and Wayland

### PR DESCRIPTION
**Pull request by murarth**
- [ ] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by murarth** [comment]
I don't have any high DPI monitors with which to test these changes, so both the X11 and Wayland implementations will need to be thoroughly tested by others.

**Comment by ZeGentzy** [comment]
@murarth Afaik, if you do some fiddling with xrandr, you could probably pretend to have a larger DPI then normal, altho I can't recall the exact command.

**Comment by ZeGentzy** [comment]
Okay, so first I tried using `--dpi` and `--fbmm`, but obviously if things worked the first time it wouldn't be X11. Anyways, I spent an hour and I found [an article](http://wok.oblomov.eu/tecnologia/mixed-dpi-x11/) mentioning using `--scale-from`, and bam, it works:

```
xrandr --output VGA-0 --scale-from 3840x2160 --right-of HDMI-A-0 --mode 1920x1080
```

And yes, of course it broke some windows on the non-scaled (HDMI-A-0) display, just take a look at keepassxc: https://imgur.com/UVt36Md.png

I also learned firefox doesn't support proper DPI support, as I can barely read this text as I type it :/.

Testing the application, the window appears to more-or-less double it's size when traveling between the two windows, as expected.

One thing of interest is that during the `resizeable` example, winit will still change the size when dragging the window between monitors. What is the intended behavior here, @Osspial ?

Due to shear lazyness, I have not tested if the window locks up during resizing, and I'm hoping on of our testers can do this. @FliegendeWurst are you up for this task? You'ld need to modify the winit examples to: 1- Use 'Poll` 2- Measure the elapsed time between events, and make sure resizing the thing vigourously doesn't stop the events from printing or cause large delays. Thanks :p

I couldn't test the wayland backend, cause I don't know how to make weston work multiscreen. I think I'd have to set up a new dm like sway and boot into that, which sounds hard. I'm not really sure how this stuff works, so maybe you can look into this, @0xpr03?

**Comment by 0xpr03** [comment]
I sadly can't seem to get the tests running on weston. No window show up in weston.

**Comment by ZeGentzy** [comment]
@0xpr03 Are you starting the examples from a terminal inside weston?

**Comment by 0xpr03** [comment]
Yes I am. It seems like mouse positions are there but no window.

**Comment by ZeGentzy** [comment]
Maybe git bisect it and find where it first breaks?

**Comment by 0xpr03** [comment]
Ok so window display broke somewhere between 0.13 and 0.15 and seems to be broken since.

**Comment by 0xpr03** [comment]
Note that the example doesn't crash. It says to have acquired a window ID, it'll also display mouse movements, just no window.

**Comment by ZeGentzy** [comment]
> Note that the example doesn't crash. It says to have acquired a window ID, it'll also display mouse movements, just no window.

That's because nothing is drawing to the window. Wayland works slightly differently. You got to test it using glutin, with a `[replace]` placed in glutin's top level `Cargo.toml`

**Comment by 0xpr03** [comment]
But why does 0.13.0 work then, with a blank window ? At least we should get the same behavior back.

**Comment by 0xpr03** [comment]
> You got to test it using glutin, with a `[replace]` placed in glutin's top level `Cargo.toml`

Using 
```
[replace]
"winit:0.20.0-alpha1" = { path = '../winit' }
```

Won't work that well, at least with this PR, as examples uses alpha-1, glutin alpha-2. This branch targets alpha-2. It might be that I'm doing something wrong but that's the state.
Also running a clean gluting in weston will panic with `eglCreateWindowSurface failed`. It works on x11 on the host.

**Comment by murarth** [comment]
I've noticed an issue on Wayland: Even when using `ControlFlow::Wait`, the event loop will constantly wake up with no events (other than `NewEvents` and `EventsCleared`). I found the cause quite easily, but I'm uncertain how to fix it.

The cause is that I've switched from using `mio` instead of `calloop` to drive the event loop, as more flexibility was required to handle the new `HiDpiFactorChanged` event. Previously, the `EventQueue` was being registered with `calloop`, but with a no-op closure to consume the data. Now, `mio` is always reporting that readable data exists on the Wayland client connection, but it's not being consumed by the main event loop.

**Comment by 0xpr03** [comment]
I'm not sure how this affects it but currently winit seems to be broken since 0.14 in wayland, showing no window. I'll try to bisect a little further tomorrow.
Sidenode: Found a eglCreateWIndowSurface crash on nvidia I can't circumvent when using glutin.

**Comment by murarth** [comment]
I've pushed a commit that I believe solves the primary Wayland issue. `EventQueue` has an implementation for the `calloop` trait `EventSource`, which reads data from the connection. Now that `mio` is used instead, winit must explicitly read data from the `EventQueue`.

**Comment by 0xpr03** [comment]
That fixes it.

**Comment by 0xpr03** [comment]
The window is now so small that it's just a titlebar, also on x11 but I think that's unrelated, or did we change something here ?

**Comment by vberger** [comment]
About no window showing on Wayland, this is actually expected behavior: the way wayland works is that a window does not appear to the screen until its contents have been drawn at least once.

In earlier versions, winit used to setup the window differently, but it caused other, more serious issues. My most recent attempt to circumvent that led to https://github.com/rust-windowing/winit/pull/981 . Ideally we'd need a wayland-specific example that draws dummy content in the window, just for tests.

And for mio, it is indeed the expected behavior, whenever it notifies that the socket is readable, winit should read & dispatch all available events.

**Comment by aleksander** [comment]
> Ideally we'd need a wayland-specific example that draws dummy content in the window, just for tests.
I'll try to reuse code from #780 to implement this.

**Comment by kchibisov** [comment]
@murarth I can help with testing on wayland with HiDPI (I have 4k and 2k monitors and can hopefully test this PR in alacritty).

Just a small note, it seems like #981 wasn't rebased to your PR. So testing things on wayland are a little bit problematic without it, since I don't know whether the issue is coming from your PR or #981. You can take a look on how alacritty renders without this fix applied [here](https://github.com/jwilm/alacritty/pull/2438#issuecomment-508165315) (screenshot in this comment).

**Comment by kchibisov** [comment]
I've run this branch on `alacritty` evlp2(3571b9c1713275545afce11d8793c3cd709bf091 this commit was force-pushed, but you can probably find it in history + manually ported `glutin`).

I'm not quite sure If I implemented all new changes correctly in `alacritty`, but at least it was running and handling dpi changes correctly, there were some startup issues from time to time on Wayland, since I'm not very familiar with new structure in evlp2 and probably missed handling of something.

However the main concern I have is that run_return API was changed a bit, so our current run_return "callback" wasn't compiling due to lifetime problems, which I've fixed for now with `std::mem::transmute`. There's a huge chance, that I've missed something. I was backporting it very fast, but you can take a look on our use of run_return [here](https://github.com/jwilm/alacritty/blob/b46c0cfba1988cadaf8cc0a700ff947722dd8299/alacritty/src/event.rs#L510) for better understanding.

cc @chrisduerr 

P.s.
FYI I can test things, but I'm not familiar with winit's Wayland/X11 code atm. I'll try to get more familiar with Wayland stuff, since I want to fix some missing features in `alacritty` on Wayland, but it'll probably take some time.

**Comment by chrisduerr** [comment]
> However the main concern I have is that run_return API was changed a bit, so our current run_return "callback" wasn't compiling due to lifetime problems, which I've fixed for now with std::mem::transmute.

This is likely unsafe. I'm not entirely certain about the changes, since it seems to infer lifetime, but if this has caused `run_return` to require a static lifetime, that would make this unusable for Alacritty.

**Comment by kchibisov** [comment]
> I don't see the transmute in that link

I've just linked our evlp2 branch and the code we're expecting to work without unsafe tricks in alacritty.

>  My hunch is that it's happening because Event now has a lifetime for the HiDpiFactorChanged event, but event_queue needs a 'static lifetime because it lasts longer than a single invocation of the event handler function.

You're absolutely correct here. In my local patched version I have to write something like this for now.

```rust
event_queue.push(unsafe { std::mem::transmute(event) });
```

I'm aware of `to_static` method, but that doesn't help us unfortunately.

**Comment by Osspial** [comment]
@kchibisov I've done some work on creating an [async event loop wrapper for Winit](https://github.com/osspial/winit-async), which lets you structure the event loop like this:

```rust
event_loop.run_async(async move |mut runner| {
    'main: loop {
        runner.wait().await;

        let mut recv_events = runner.recv_events().await;
        while let Some(event) = recv_events.next().await {
            match event {
                Event::WindowEvent {
                    event: WindowEvent::CloseRequested,
                    ..
                } => {
                    break 'main;
                },
                _ => println!("{:?}", event),
            }
        }

        window.request_redraw();

        let mut redraw_requests = recv_events.redraw_requests().await;
        while let Some(window_id) = redraw_requests.next().await {
            println!("redraw {:?}", window_id);
        }
        println!();
    }
})
```

That work isn't complete, and it hasn't been integrated with the DPI upgrades yet, but once that's integrated you may be able to use that to get rid of the event buffer entirely and avoid the safety issues you're running into.

**Comment by Osspial** [comment]
What's the status on this?

**Comment by ZeGentzy** [comment]
> I'm not quite sure If I implemented all new changes correctly in `alacritty`, but at least it was running and handling dpi changes correctly, there were some startup issues from time to time on Wayland, since I'm not very familiar with new structure in evlp2 and probably missed handling of something.

I suspect the startup issues are from the backporting or some other bug. I think this is good to merge, no?

**Comment by kchibisov** [comment]
FYI, startup issues are due to this https://github.com/rust-windowing/winit/issues/1119

**Comment by chrisduerr** [comment]
@murarth Just out of curiosity, is there a reason why the `HiDPIFactorChanged` event requires a borrow? It seems like it should be `Copy`, right?

**Comment by murarth** [comment]
@chrisduerr I'm just following the API as designed. I raised that same question in the tracking issue: https://github.com/rust-windowing/winit/issues/939#issuecomment-515527427

**Comment by chrisduerr** [comment]
I guess I just don't understand why we would want to modify a mutable reference in the HiDPI event to change the window size. It seems like that could be extremely confusing an unexpected behavior.

It seems like it would be way easier to just change the window size explicitly on the window.

However I'm sure @ZeGentzy had a good reason for this, possibly requested by other dowstream users. So this PR is not really the best place to discuss this, sorry.

**Comment by Osspial** [comment]
@chrisduerr I was the one that made the decision to include a lifetime, and here's my main reasons for doing that:

1. This is by far the cleanest way for us to implement it internally and expose it as an API. The resizing logic can behave significantly differently when you're resizing in response to a DPI switch, and there's no way for us to reliably account for that once the event handler is over. Using a lifetime forces the user to set it at the right time so we can handle the resize properly.
2. We're likely going to need to introduce a lifetime to expose other events cleanly ([`Sizing` comes to mind](https://github.com/rust-windowing/winit/pull/695#issuecomment-450904674)), so introducing it here is a good way to make the major breaking change and minimize disruption in the future. `HiDpiFactorChanged` benefits from the lifetime as illustrated above, so it's a natural place to do that.

**Pull request merged**
