### PR TITLE
[WIP] Macos Evlp2

### PR DESCRIPTION
**Pull request by ZeGentzy**
I kind of fucked up and had to manually back port changes. Git is hard. It will all get squashed in the end, so doesn't matter.

I think this is correct, or maybe not. All I know is it compiles :)

### CODE REVIEW

**Comment by ZeGentzy** [comment]
cc @ryanisaacg

**Comment by ZeGentzy** [comment]
I don't even know why it pulled in the x11 things, and I don't know how to fix it.

**Comment by Osspial** [comment]
I've got basically no knowledge of how cocoa works nor an ability to test stuff, so unfortunately I'm unable to review this.

**Comment by ryanisaacg** [comment]
I've checked the `window` example and the printed events look right, `resize` works, `multiwindow` works, `min_max_size` works, `monitor_list` works, etc. For now it looks good to me!

Once glutin supports events loop 2.0 and once I move Quicksilver over to events loop 2.0, I can test to see if it introduces any regressions there.

**Comment by ZeGentzy** [comment]
@ryanisaacg You're in luck: https://github.com/rust-windowing/glutin/pull/1146

Windows also compiles. Maybe you could test that, @Osspial ?

**Comment by ryanisaacg** [comment]
Having ported Quicksilver to EventLoop 2.0, I can pretty confidently say the macOS backend works.

**Comment by ZeGentzy** [comment]
Splendid. Ready for merge, @Osspial, or do you have any objections?

**Comment by Osspial** [comment]
Nope. As a side note, this means that ***all the desktop backends for EL2.0 are done!*** :tada: :tada: :tada:

I'd like to address #728 and #794 before it gets onto crates.io, but.... yeah. Good work, everyone. It's been a long time coming.

**Comment by vberger** [comment]
Question though, did this PR include the backport of the changes made to the master branch since it diverged with eventloop-2.0 ?

**Comment by ZeGentzy** [comment]
I had to backport the following manually:
9a23ec3
45a4281
bfbcab3

The rest (checked every commit since 2018 which touched the macos files) were already included, assuming I didn't make a mistake and miss something.

@Osspial What's the plan wrt the mobile backends, and emscripten?

**Comment by Osspial** [comment]
I want to get the iOS backend merged since... well, it [exists and works](https://github.com/mtak-/winit/tree/events_loop_2.0_ios), but I'd like @mtak- to submit a PR for that since they wrote it. Other than that, I don't think Android and Emscripten are used widely enough to block the `crates.io` release, especially since we don't have anyone working on them at the moment - ideally they'd be included, of course, but it'll simplify the maintenance drastically to just have all the development be against `master` instead of having two active branches.

Also, I'd be comfortable with blocking the release on #797 depending on the timeline for getting that done. Don't have much of a sense for that, though. (cc @ryanisaacg)

**Comment by ryanisaacg** [comment]
At this point I'm mostly working on additions to stdweb to support features winit needs, which means that I'm largely bottlenecked on getting those changes merged and released. I'm not sure how long that will take, so if I start holding up the release I would say go ahead without web.

**Pull request merged**
