### PR TITLE
Add ModifiersChanged event for macOS

### PR DESCRIPTION
**Pull request by chrisduerr**
This implements the macOS portion of #1124.

### CODE REVIEW

**Comment by murarth** [comment]
With #1262 merged, this needs to be updated to generate `ModifiersChanged` as a `DeviceEvent`.

**Comment by chrisduerr** [comment]
Should be good to go now. Thanks for the note @murarth.

**Comment by chrisduerr** [comment]
> @chrisduerr could you update CHANGELOG.md with this changes, please?
Otherwise it's ready for merge.

I intentionally did not add this to the changelog, because the X11 commit held out on a changelog addition until it is supported on all platforms.

**Comment by chrisduerr** [comment]
@vbogaevsky Any update on how to proceed? Should I add a changelog or not?

Or wait until the Windows PR is sent to finish things off?

**Comment by vbogaevsky** [comment]
@chrisduerr I'm merging this PR, and lets add changes to CHANGELOG.md in Windows PR.

**Pull request merged**
