### PR TITLE
Fix thread-safety of `set_maximized` and `set_title` on macOS

### LINKED ISSUE #905: `multithreaded` example crashes on key press on macOS
Pressing any keys when running the `multithreaded` example from `eventloop-2.0` will crash on macOS.

Sometimes it produces a segmentation fault and other times it produces a panic.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0:        0x1096a2b83 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf2949dcf16da83bd
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:        0x10969eca2 - std::sys_common::backtrace::_print::h4b87ed6ba0cd5304
                               at src/libstd/sys_common/backtrace.rs:71
   2:        0x1096a1b26 - std::panicking::default_hook::{{closure}}::hde39fed432870543
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:        0x1096a18cf - std::panicking::default_hook::hfce8820d41dbdcbf
                               at src/libstd/panicking.rs:211
   4:        0x1096a229f - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h7aefec6ee3a0deaf
                               at src/libstd/panicking.rs:474
   5:        0x1096a1dcc - std::panicking::continue_panic_fmt::h4d668741ea600293
                               at src/libstd/panicking.rs:381
   6:        0x1096a1cb8 - std::panicking::try::do_call::h1252fc9a2ff235eb
                               at src/libstd/panicking.rs:308
   7:        0x1096b6ae1 - <T as core::any::Any>::type_id::h2f1dfe6f5ac846ab
                               at src/libcore/panicking.rs:85
   8:        0x1096b6a26 - <T as core::any::Any>::type_id::h2f1dfe6f5ac846ab
                               at src/libcore/panicking.rs:49
   9:        0x1096a497b - panic_unwind::dwarf::eh::read_encoded_pointer::hf5b0123b85857914
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/macros.rs:12
                               at src/libpanic_unwind/gcc.rs:91
                               at src/libpanic_unwind/lib.rs:90
  10:        0x10942da14 - std::panicking::try::hfa151a0f5c16c8bc
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272
  11:        0x10943bd8f - std::panic::catch_unwind::hda7deb41f7a68c84
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388
  12:        0x10943babd - std::thread::Builder::spawn_unchecked::{{closure}}::h7b8f56d6f4049637
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/thread/mod.rs:469
  13:        0x10944b8f4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4224278819b07abf
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231
  14:        0x109697f4d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf8766009c029bc09
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  15:        0x1096a3f2d - std::sys::unix::thread::Thread::new::thread_start::hfdef4649a42cf26c
                               at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:80
  16:     0x7fff619eb304 - _pthread_body
  17:     0x7fff619ee26e - _pthread_start
fatal runtime error: failed to initiate panic, error 5
[1]    71246 abort      RUST_BACKTRACE=full cargo run --example multithreaded
```

### PR DESCRIPTION
**Pull request by aleksijuvani**
Fixes #905. See https://github.com/rust-windowing/winit/issues/905#issuecomment-501990074. I'm not sure if this should be added to the changelog, or if this is specific to the `eventloop-2.0` changes, seeing as how the "multithreaded" example does not exist in the previous branch.

- [x] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/tomaka/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by Osspial** [comment]
AFAIK none of the maintainers have easy access to OSX hardware we're unable to test this, but skimming through the code I can't see any problems. @felixrabe iirc you run an OSX setup - could you quickly test this before we merge it?

**Comment by felixrabe** [comment]
Working on it.

I've put up a rebased version of this pull request at https://github.com/rust-windowing/winit/compare/master...felixrabe:fix-mac-multithreaded.

**Comment by jdm** [comment]
@osspial I also have easy macOS access and can test changes when necessary.

**Comment by felixrabe** [comment]
(This is on macOS 10.13:) I've run `cargo check` and `cargo test` and several examples against both master (plus some fixes against warnings) and against this PR (or rather my rebased version, plus same warning fixes).

So far I see that `example/multithreaded` stopped crashing on pressing `M` (the other keys were working for me on master). I *did* get another crash, but could not reproduce so far.

I collected a bunch of other issues unrelated to this one.

**Comment by Osspial** [comment]
@felixrabe Thanks for resolving the conflict, but I'd rather get it resolved in this PR and merge it here. Creating a separate PR to resolve merge conflicts seems like a last-resort sort of move, and I'd like to avoid setting precedent for it if at all possible.

**Comment by aleksijuvani** [comment]
I've rebased this against `master`.

**Comment by ZeGentzy** [comment]
Merging since this was tested.

**Pull request merged**
