### PR TITLE
On Wayland, add missing virtual key codes mappings

### PR DESCRIPTION
**Pull request by kchibisov**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

cc @vberger

### CODE REVIEW

**Comment by vberger** [comment]
I'm ok with these changes, however I notice there is some inconsistency in the handling of keys of the first row in winit.

Historically these keys were always matched to the numbers, irrespective of the actual keymap. In a game-oriented fashion.

Now, for some platforms winit no longer does this and just follow the keymap, for others it still does. Like macos for example:

https://github.com/rust-windowing/winit/blob/9e3844ddd9b31a083d1a2089c70be17aa4ed5787/src/platform_impl/macos/event.rs#L67-L76

This PR also removes this behavior for Wayland, which currently still has it. Is there something decided about that ? @Osspial @goddessfreya

**Comment by kchibisov** [comment]
>Now, for some platforms winit no longer does this and just follow the keymap, for others it still does. Like macos for example:

I wouldn't count macOS here, since its events are completely broken most of the time and for example alacritty has all the bugs due to that, note, you've linked a bit wrong code here, since the thing Wayland was doing is the same as Scancode to VirtualKeyCode mapping, which is here 
https://github.com/rust-windowing/winit/blob/1f24a09570d3bf0a39af836c3a7c212a0b65ff70/src/platform_impl/macos/event.rs#L112-L124

But it also doesn't get executed in some cases, and the code you've linked is the exact this case, when it decides to do something differently, it maps character it got from macOS to a VirtualKeyCode, so there's no guarantee that "1" was physically `1` under the hood.

Anyway, I'd like to wait here for maintainers as well.

**Comment by lovesegfault** [comment]
I applied this diff to `glutin`:
```patch
diff --git a/glutin/Cargo.toml b/glutin/Cargo.toml
index 10d580b..5593f28 100644
--- a/glutin/Cargo.toml
+++ b/glutin/Cargo.toml
@@ -18,7 +18,7 @@ serde = ["winit/serde"]
 
 [dependencies]
 lazy_static = "1.3"
-winit = "0.22.0"
+winit = { git = "https://github.com/kchibisov/winit", branch = "wayland-keysyms" }
 
 [target.'cfg(target_os = "android")'.dependencies]
 android_glue = "0.2"
diff --git a/glutin_examples/Cargo.toml b/glutin_examples/Cargo.toml
index 49faae0..3d35945 100644
--- a/glutin_examples/Cargo.toml
+++ b/glutin_examples/Cargo.toml
@@ -12,7 +12,7 @@ publish = false
 
 [dependencies]
 glutin = { path = "../glutin" }
-winit = "0.20.0"
+winit = { git = "https://github.com/kchibisov/winit", branch = "wayland-keysyms" }
 takeable-option = "0.4"
 image = "0.21"
 ```

And proceeded to try the `window` example, but the results were the same as reported in #1533, no virtual keycodes show up. Logs: 

```
NewEvents(WaitCancelled { start: Instant { tv_sec: 48810, tv_nsec: 113933706 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 30, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48810, tv_nsec: 114025276 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48810, tv_nsec: 457933180 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 31, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48810, tv_nsec: 458021348 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48810, tv_nsec: 597929953 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 31, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48810, tv_nsec: 598019035 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48811, tv_nsec: 219856410 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 32, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48811, tv_nsec: 219947645 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48811, tv_nsec: 371926522 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 32, state: Released, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48811, tv_nsec: 372014896 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48812, tv_nsec: 547937773 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 126, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48812, tv_nsec: 548027877 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48812, tv_nsec: 855930938 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: None, modifiers: (empty) }, is_synthetic: false } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48812, tv_nsec: 856020114 }, requested_resume: None })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 48813, tv_nsec: 683847196 }, requested_resume: None })
WindowEvent { window_id: WindowId(Wayland(WindowId(94879317467360))), event: CloseRequested }
MainEventsCleared
RedrawEventsCleared
LoopDestroyed
```

**Comment by kchibisov** [comment]
We've already figured out with @lovesegfault on IRC, that his issue was due to NixOS and rpath.

**Comment by JMS55** [comment]
Is this PR waiting on anything? This would be useful to me, as for my game, I use the period `.` key, but it doesn't work on Wayland currently.

**Comment by carlsmedstad** [comment]
Also wondering if this is waiting on something.

I rebased this change on master with no conflicts, built Alacritty with it and it does indeed solve https://github.com/alacritty/alacritty/issues/3998.

**Comment by kchibisov** [comment]
Since there was no concerns being made this PR will be a part of #1653.

**Pull request closed without merging**
