### PR TITLE
fixed nsmenu activation bug

### PR DESCRIPTION
**Pull request by adamnemecek**
I'm looking to get feedback on this. I'm not sure if the commented out is necessary, but the menu seems to work fine.

### CODE REVIEW

**Comment by adamnemecek** [comment]
@ArturKovacs @madsmtm do you guys want to verify this? i saw @madsmtm but it doesn't quite fix it.

**Comment by maroider** [comment]
So this is meant as an alternative to #1903, right?

**Comment by adamnemecek** [comment]
#1903 doesn’t work for me. Does it for you?

**Comment by maroider** [comment]
I don't have a mac, so I can't really test either PR. I've just got this repo set to "watch all activity".

**Comment by ArturKovacs** [comment]
Awesome work! Do you mind me pushing to this branch?

**Comment by adamnemecek** [comment]
I don’t mind but are you sure we don’t care about the code I uncommented? Are you on discord? I’d like to discuss some other nsmenu matters.

**Comment by ArturKovacs** [comment]
I'm ArturBarnabas#8576 on discord, I wrote to someone, who I believe is you @adamnemecek

**Comment by lemarier** [comment]
GUYS!!!! IT WORKS 💯 

At @tauri-apps we are blocked by this !!!!

**Comment by ArturKovacs** [comment]
@adamnemecek please check if my changes look good.

**Comment by lemarier** [comment]
Well done! Works fine here. Tested with multi-window as well!

**Comment by ArturKovacs** [comment]
@adamnemecek you seem to be pretty competent at this stuff are you interested in becoming a winit maintainer? @francesca64

**Comment by adamnemecek** [comment]
Sure. It’s a thankless job but someone has to do it.

**Comment by ArturKovacs** [comment]
> Tested with multi-window as well!

Oh no! I just tested that as well and now only the first window shows up. All windows show up on the `master` branch. Will have to spend some more time with this...

**Comment by lemarier** [comment]
> > Tested with multi-window as well!
> 
> Oh no! I just tested that as well and now only the first window shows up. All windows show up on the `master` branch. Will have to spend some more time with this...

Here's the 3 windows are created and show's, I wonder if it's not because they are hidden behind another window?
Running `11.2.3`

**Comment by madsmtm** [comment]
Honestly, at this point I'm beginning to think the examples are the fault; things work as they should if you create the windows after `applicationDidFinishLaunching`:

```rust
Event::NewEvents(event) if event == StartCause::Init => {
    for _ in 0..3 {
        let window = Window::new(&event_loop).unwrap();
        windows.insert(window.id(), window);
    }
}
```

Maybe it's just not possible to create windows in a clean way, where they show up from the beginning, without resorting to weird hacks?

**Comment by madsmtm** [comment]
Also, can you please state your MacOS versions? Because there's no difference between #1903 and this on my machine (MacOS 10.14.6 Mojave), but as I said in the linked issue, we would probably have to do something similar to https://github.com/linebender/druid/pull/994 to support higher versions - but it would be nice to know if it is indeed a version-dependent thing!

**Comment by adamnemecek** [comment]
I’m on Big Sur. This fix is in fact the same thing as what Druid is doing.

**Comment by ArturKovacs** [comment]
I'm on macOS 10.11. And just to clarify I'm affected by both the menubar not activating and windows not showing up.

> I wonder if it's not because they are hidden behind another window?

I start up the example then drag and move the first window away from its initial position and there's no window behind it. Then I close it and a new window suddenly appears at the original spot.

**Comment by casperstorm** [comment]
> I'm on macOS 10.11. And just to clarify I'm affected by both the menubar not activating and windows not showing up.
> 
> > I wonder if it's not because they are hidden behind another window?
> 
> I start up the example then drag and move the first window away from its initial position and there's no window behind it. Then I close it and a new window suddenly appears at the original spot.

Just to tip in: I'm on 10.15 and it is working for me, both single and multiwindow.

**Comment by ArturKovacs** [comment]
Closing as this was superseded by #1903 and #1922

**Pull request closed without merging**
