### PR TITLE
Macos fullscreen & dialog support with `run_return`

### PR DESCRIPTION
**Pull request by VZout**
Previously the `run_return` example would freeze if you switch to fullscreen. This fixes it.
It is not a clean solution but if anybody knows more about mac than I do let me know if there is a better way.

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by VZout** [comment]
Rewrote my approach since I noticed I caused a bug with the control flow.

**Comment by VZout** [comment]
Also added experimental dialog/child window support tested with https://github.com/EmbarkStudios/nfd2.

**Comment by VZout** [comment]
@kchibisov @francesca64  You two originally authored the `run_return` implementation for Macos. What do you guys think about this issue?

**Comment by kchibisov** [comment]
I don't have native macOS machine and don't know much about macOS. The run_return impl is a copypasta of run impl. I'm not sure If I ever seen a freeze from run_return, since we're using it for so much time in alacritty, and no one ever reported it. Maybe I don't understand the conditions where it should freeze?

**Comment by VZout** [comment]
@kchibisov So its 2 issues. 1 is running the `window_run_return` sample and pressing the green fullscreen button on mac. It completely freezes the app. The second is that opening dialogs using `nfd2` also freezes the app. 

This PR solves both but not in a very clean way.

**Comment by francesca64** [comment]
@VZout while I wrote the macOS EL2 backend, I never included a `run_return` implementation, since I felt it wouldn't be idiomatic on macOS and that there'd likely be complications.

My perspective might be poisoned from having to write so many workarounds in my life, but I honestly don't think this looks _that_ unclean. While a canonical solution could exist, it'd likely involve a considerable amount of research into what other windowing implementations are doing.

**Comment by Jasper-Bekkers** [comment]
> @VZout while I wrote the macOS EL2 backend, I never included a run_return implementation, since I felt it wouldn't be idiomatic on macOS and that there'd likely be complications.

For various reasons we can't have winit really take control of our application loop like that. It would be a welcome addition to have `run_return` available on all platforms that would support it.

I also don't think this code is super unclean, so I'd love to see this get merged into mainline.

**Comment by francesca64** [comment]
@Jasper-Bekkers 
> It would be a welcome addition to have run_return available on all platforms that would support it.

I believe that's already the current story.

@vbogaevsky are you around for an additional review?

**Comment by VZout** [comment]
I've fixed a minor issue. A colleague noticed that maocs dialogs were not being closes properly and always exited with the canceled event.

**Pull request merged**
