### PR TITLE
Improve waiting for messages on Windows [PR to 0.30.x branch]

### PR DESCRIPTION
**Pull request by AngelicosPhosphoros**
Previous version used `CreateTimer` with `GetMessageW` for waiting. The downside of UI timers like ones created by `CreateTimer`, is that they may be late by up to 15-16 ms.

To fix this behaviour, I added use of high precision timers created by [`CreateWaitableTimerExW`] with the flag `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION`. In my previous experience, waiting on such timers have precision of roundly 0.5 ms which is the best available on Windows at the moment. I use [`MsgWaitForMultipleObjectsEx`] to wait simultaneously for both timer and newly arriving events.

Unfortunately, high precision timers are available only since Windows 10 1803. However:

1. Win 10 is already getting to the end of support, like all previous versions, so it is OK to rely on APIs introduced in it;
2. I use `dwMilliseconds` parameter of `MsgWaitForMultipleObjectsEx` as a fallback. It should perform not worse compared to waiting for events from [`CreateTimer`].

I also refactored code to remove event dispatching from function responsible for waiting for events. This provides more clear separations of concern and avoids unnecessary duplication of dispatching logic.

I have tested behaviour using a egui app with Vulkan rendering with `VK_PRESENT_MODE_IMMEDIATE_KHR`, and older version consistently have twice less FPS than requested (e.g. 30 FPS when limit is 60 and 60 FPS when limit is 120) while newer version works more correctly (almost always 60 FPS when limit is 60, and only 5-10 frames missing whne FPS is set to 120 or more).

Fixes https://github.com/rust-windowing/winit/issues/1610

[`CreateWaitableTimerExW`]: https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerexw
[`MsgWaitForMultipleObjectsEx`]: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-msgwaitformultipleobjectsex

- [x] Tested on all platforms changed
- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by AngelicosPhosphoros** [comment]
#### Current version in crates.io:

https://github.com/user-attachments/assets/bf52ce3e-c05d-4afa-b8c4-a20784b0e98d

#### With my changes:

https://github.com/user-attachments/assets/412e502d-ca59-43b8-a222-1778fa043553

**Comment by AngelicosPhosphoros** [comment]
I don't know why but when I run `cargo fmt` locally, it changes bunch of files except the one changed in PR.

**Comment by kchibisov** [comment]
Please, open your changes against the master branch.

You should use the nightly formatting.

**Comment by AngelicosPhosphoros** [comment]
I can also open PR to merge to current master, if you wish but I don't have a project ready to test on master.

Also, CI failures point not to my code but to the code that was here before. I think, it is unrelated.

**Comment by AngelicosPhosphoros** [comment]
@kchibisov  If my code gets merged to master, would those changes be ported and released as 0.30.x? I just finished migration to 0.30.x and I fear that I would need to wait long time for egui and egui-winit to catch up.

**Comment by AngelicosPhosphoros** [comment]
Opened PR to master: https://github.com/rust-windowing/winit/pull/3950

**Comment by kchibisov** [comment]
I don't see why not. The only issue is that we currently lack active windows maintainer, so getting things reviewed could be a bit _hard_, unless e.g. @notgull wants to look into that.

I myself don't really look into windows stuff.

**Comment by kchibisov** [comment]
Closing in favor of #3950.

**Pull request closed without merging**
