### PR TITLE
example: Add an example of `request_inner_size`

### PR DESCRIPTION
**Pull request by ColinKinloch**
This adds the shortcut "Alt + R" to swap the size of the window axes.

I'm seeing a number of winit clients that ignore the output of `request_inner_size` on wayland. I hope having this in the example will change this.

- [ ] Tested on all platforms changed
- [ ] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by kchibisov** [comment]
If they ignore `must_use` I'm not sure it could be helped.

Though, example updates are welcome.

**Review by kchibisov — APPROVED** [review]
Rebased and reformatted a bit, should be good now.

**Review by madsmtm — APPROVED** [review]
Seems like mostly a Wayland thing, so fine by me

**Comment by kchibisov** [comment]
Thanks.

**Pull request merged**
