### PR TITLE
Check whether CoCreateInstance succeeds

### LINKED ISSUE #2701: Visual studio debugger crashes on `set_skip_taskbar`
Whilst trying out the new visual studio plugin for rust I found a crash in `set_skip_taskbar`. It only appears appears on debug builds. The bug seems to be related to `CoCreateInstance` returning a null pointer, since it isn't being checked.

I tried set `set_skip_taskbar` to true but that doesn't seem to change the behavior.
I'm using visual studio 2022 preview with winit version 0.28.1 on windows 11.

### PR DESCRIPTION
**Pull request by WINSDK**
Fixes #2701

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Review by msiglreith — APPROVED** [review]
thanks!
I will merge it once the keyboard rework PR lands to reduce friction

**Comment by kchibisov** [comment]
I think it's fine that way, given it's a crash fix.

**Review by kchibisov — CHANGES_REQUESTED** [review]
We'd need a CHANGELOG entry for that.

**Review by kchibisov — APPROVED** [review]

**Comment by WINSDK** [comment]
Added a CHANGELOG entry.

**Comment by kchibisov** [comment]
Thanks!

**Pull request merged**
