### PR TITLE
More concise `Debug` output for `WindowId`.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Since this is a nested struct, it was printing
`"WindowId(WindowId(2834882))"` when just printing `"WindowId(2834882)"` would be sufficient.

- [ ] Tested on all platforms changed
- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I did try this out on macOS but don't have other platforms handy at the moment. I didn't think this was the sort of thing that you'd add a test for, but could do so.

**Review by madsmtm — CHANGES_REQUESTED** [review]
Hmm, I've considered doing this myself, and it's a problem with the `Debug` outputs for all of the other public structs as well, but honestly, I'd rather just use the `derive`d version of this, it more accurately represents what the code is like.

**Review by notgull — APPROVED** [review]
I take the opposite position; we should avoid cluttering up the debug output.

**Comment by waywardmonkeys** [comment]
@madsmtm You marked this as needing a change, but I'm not clear what the change would be (especially as you indicated you didn't want it).

**Review by kchibisov — APPROVED** [review]
Fine by me.

Though, I'd suggest to check other top-level types, since there're plenty of them which look like that.

In the long term, the nesting will go away entirely.

**Review by madsmtm — APPROVED** [review]
No code changes, I just didn't really want this. But if others are fine with it, then I won't block.

**Review by daxpedda — APPROVED** [review]

**Pull request merged**
