### PR TITLE
On Web, fix context menu not being disabled by `with_prevent_default(true)` (backport to v0.29.6)

### PR DESCRIPTION
**Pull request by daxpedda**
See https://github.com/rust-windowing/winit/pull/3282.

### CODE REVIEW

**Comment by kchibisov** [comment]
Does it really matter that much?

**Comment by kchibisov** [comment]
I mean, to make another release with just this change given that it was broken for all the patch releases and no-one complained about. I'd just offset it with the 0.29.6 which may include some other patches.

**Comment by daxpedda** [comment]
No, this is definitely not worth a separate patch release.
Ofc, feel free to close it if you wanna cherry pick it yourself later.

**Comment by kchibisov** [comment]
applied.

**Pull request closed without merging**
