### PR TITLE
Examples: less redundancy, improve fullscreen

### PR DESCRIPTION
**Pull request by dhardy**
Added [softbuffer](https://crates.io/crates/softbuffer) as a dev-dependency, as discussed in #2246. This is only one new example; I'm not sure it has a lot of utility. (It would be nice to see this used in at least `examples/transparency`, but this didn't work and due to the simple nature of the `softbuffer` crate I opted not to investigate further.)

Improved input handling of `examples/fullscreen` (expecting use of the console for input while in fullscreen mode is not user friendly).

Removed three examples which are redundant with others.

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by dhardy** [comment]
You don't like the colour? I just copied the code from the `softbuffer` example:
softbuffer

Sure, I can merge this with what was `window`.

**Comment by dhardy** [comment]
I can fix that, but I believe there's a more pressing issue: all the windows tests have failed due to a softbuffer build issue. I don't think we want winit to suffer due to this, and dev-dependencies cannot be optional. I guess I could use a separate crate for the example, but then it's not just `example/window.rs`. Or I can just remove `softbuffer`. Or we can really try to fix `softbuffer`. Thoughts?
```
   Compiling softbuffer v0.1.1
     Running `rustc --crate-name softbuffer --edition=2021 'C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\softbuffer-0.1.1\src\lib.rs' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f3ec2003a81d19db -C extra-filename=-f3ec2003a81d19db --out-dir 'D:\a\winit\winit\target\x86_64-pc-windows-msvc\debug\deps' --target x86_64-pc-windows-msvc -L 'dependency=D:\a\winit\winit\target\x86_64-pc-windows-msvc\debug\deps' -L 'dependency=D:\a\winit\winit\target\debug\deps' --extern 'raw_window_handle=D:\a\winit\winit\target\x86_64-pc-windows-msvc\debug\deps\libraw_window_handle-372dbe4082903639.rmeta' --extern 'thiserror=D:\a\winit\winit\target\x86_64-pc-windows-msvc\debug\deps\libthiserror-2bea0a258ade75d0.rmeta' --extern 'winapi=D:\a\winit\winit\target\x86_64-pc-windows-msvc\debug\deps\libwinapi-98ef40f9f3dc86ea.rmeta' --cap-lints allow -C debuginfo=0 --deny warnings`
error[E0432]: unresolved import `winapi::um::winuser`
Error:  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\softbuffer-0.1.1\src\win32.rs:6:17
  |
6 | use winapi::um::winuser::{GetDC, ValidateRect};
  |                 ^^^^^^^ could not find `winuser` in `um`
For more information about this error, try `rustc --explain E0432`.
error: could not compile `softbuffer` due to previous error
```

**Comment by dhardy** [comment]
Since I lack a Windows machine for testing, I'll have to leave the fixing to others.

**Comment by dhardy** [comment]
I rebased: softbuffer is now only used in examples/window

**Comment by dhardy** [comment]
Sure. Would it make more sense to push softbuffer integration to a different PR in that case, and merge the other changes here?

**Comment by kchibisov** [comment]
>Sure. Would it make more sense to push softbuffer integration to a different PR in that case, and merge the other changes here?

Sure.

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
