### PR TITLE
add: Hacky `cfg` `winit_ignore_noisy_logs_unstable`

### PR DESCRIPTION
**Pull request by ActuallyHappening**
- [ ] Tested on all platforms changed
- [ ] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

Helps address #3714.
Preferably the underlying issue could be fixed, but this is enough to satisfy my use case

### CODE REVIEW

**Comment by daxpedda** [comment]
Considering we're using `tracing` now, Shouldn't this be filterable on the user level?

(can look into it when I get home)

**Comment by ActuallyHappening** [comment]
You can do it yes, although it is not easily possible. You can't use an `EnvFilter` string like `info,[{message="very annoying log message here"}]=error` because the `tracing::warn!("very annoying log message here")` is matched by the `info` first.
If it is possible to filter away this on the user side, I would very much like to know! But I've read the `EnvFilter` docs (https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html) a few times and haven't noticed anything :(

**Comment by daxpedda** [comment]
So it should be possible with using [Metadata filtering](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/layer/index.html#enabling-interest). There's a bunch of examples in the documentation using [`with_filter()`](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/layer/trait.Layer.html#method.with_filter).

You should also be able to simply [turn off all warnings in the desired module](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/filter/targets/struct.Targets.html#examples), which is much more blunt.

**Comment by ActuallyHappening** [comment]
> So it should be possible with using [Metadata filtering](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/layer/index.html#enabling-interest). There's a bunch of examples in the documentation using [`with_filter()`](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/layer/trait.Layer.html#method.with_filter).
> 
> You should also be able to simply [turn off all warnings in the desired module](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/filter/targets/struct.Targets.html#examples), which is much more blunt.

Ahh thank you very much! This is very useful and should hopefully solve my problem. Using `bevy`'s [`LogPlugin`](https://docs.rs/bevy/latest/bevy/log/struct.LogPlugin.html#structfield.update_subscriber) should be able to do this.

**Pull request closed without merging**
