### PR TITLE
Fix inconsistency in mouse button device events, add hwheel device event on Windows

### PR DESCRIPTION
**Pull request by valaphee**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

While working with device events, I noticed that there was an inconsistency in the mouse button device events between Windows/X11 and for example web, because web uses the same ids/order as the MouseButton enum, and Windows/X11 are using the X11 ids, and hwheel device event was ignored on Windows.

Mouse button device events are now using the same order as the MouseButton enum, and I also added hwheel device events for Windows.

### CODE REVIEW

**Review by notgull — CHANGES_REQUESTED** [review]
If the documentation [here](https://www.x.org/releases/current/doc/inputproto/XI2proto.txt) is correct, it says that `detail` might not correspond 1:1 with the mouse press.

> detail: The button number, keycode or touch ID

In addition to the fact that my understanding is that the "raw" device events are intended to correspond 1:1 with the underlying driver data (this isn't possible on Web), so modifying it shouldn't happen. As in, for device events, you really shouldn't be trying to interpret the data directly unless you have a pretty good guess for what the device is.

The windows code looks good to me.

**Comment by valaphee** [comment]
Thanks for the input, I removed the remapping of mouse button ids in X11. Both platforms now return "unmodified" device events.

**Review by kchibisov — APPROVED** [review]

**Comment by kchibisov** [comment]
@valaphee could you rebase?

**Review by notgull — APPROVED** [review]
Thanks!

**Pull request merged**
