### PR TITLE
Release 0.27.3 version

### PR DESCRIPTION
**Pull request by kchibisov**
I'd like to sort out `raw-window-handle` and also #2484 and should be good to go after that.

### CODE REVIEW

**Comment by kchibisov** [comment]
If anyone feels like we should include more stuff in the patch release, feel free to propose it here. But I've tried to apply only required patch commits.

**Comment by madsmtm** [comment]
I don't have any blockers

**Comment by kchibisov** [comment]
I'll wait for #2489 to at least understand what I should do with the version on master after I'll bump this.

**Comment by ar37-rs** [comment]
@kchibisov wait wait, my PR not reviewed yet #2490

**Comment by madsmtm** [comment]
@ar37-rs I'd really like to keep features out of patch releases - let's handle your PR as usual, and then it will land in `v0.28.0`.

**Comment by ar37-rs** [comment]
@madsmtm Ok, i want that feature so badly.  hope it will be landed on v0.28.0 regardless of who will make the PR.

**Pull request merged**
