### PR TITLE
Report mouse motion before click

### LINKED ISSUE #942: No mouse events when unfocused on macOS
This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2475.

It looks like winit does not report mouse movements inside the window if it is currently unfocused. This makes it difficult to track mouse click positions since the mouse can "teleport" into position without being able to track it.

If this is an intentional design decision, I think that there's no way around reporting mouse position on click events, since a click might come in without any previous motion events at all.

This could be resolved with https://github.com/rust-windowing/winit/issues/883, but it might still make sense to report motions above the unfocused window, since I'm pretty sure other platforms do that?

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes an issue on macOS where a mouse click would be generated,
without ever getting a mouse motion to the position before the click.
This leads to the application thinking the mouse click occurred at a
position other than the actual mouse location.

This happens due to mouse motion above the window not automatically
giving focus to the window, unless it is actually clicked, making it
possible to move the window without motion events.

Fixes #942.

### CODE REVIEW

**Comment by SergeevPavel** [comment]
Could we also trigger mouse motion before mouse wheel event?

**Comment by chrisduerr** [comment]
I've added it for pressure change and scroll too, since that makes some sense.

**Comment by chrisduerr** [comment]
Test failure on Windows should be unrelated to this macOS PR.

**Comment by ryanisaacg** [comment]
I merged master into this branch which should solve the CI conflicts and get this ready for a merge.

**Comment by QuentinPerez** [comment]
I have the same issue thank you for the patch, I was wondering if we could add x and y in the mouseClick event instead of doing magic by saving the last x,y sent by the last Mouse::CursorMoved ?

**Comment by ryanisaacg** [comment]
@QuentinPerez Do you mean in the external Winit API?

**Comment by QuentinPerez** [comment]
Yes, like https://github.com/rust-windowing/winit/blob/849b8f5dce4d3f93b251259f5323ea9fd43e0c05/src/event.rs#L256 but for https://github.com/rust-windowing/winit/blob/849b8f5dce4d3f93b251259f5323ea9fd43e0c05/src/event.rs#L277, don't know if it's the best way to do things.

**Comment by ryanisaacg** [comment]
@QuentinPerez That discussion is probably best for a meta-issue on the tracker, like [this previous issue.](https://github.com/rust-windowing/winit/issues/883). This PR is fixing an internal bug regarding emitting the `CursorMoved` on macOS, specifically.

**Pull request merged**
