### PR TITLE
macOS: Don't change fullscreen state during fullscreen transition

### LINKED ISSUE #1269: Toggling fullscreen on Mac errors if Command key is held
If you take a minimal sample for toggling borderless fullscreen via keyboard shortcut, and you require the shortcut to include the Command key, Mac OS will print errors to the console when exiting fullscreen, accompanied by the system alert sound.

```
2019-11-09 18:28:30.309 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:31.991 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:33.518 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:35.101 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
2019-11-09 18:28:37.041 winit-exit-fullscreen-mac[17038:239253] not in fullscreen state
```

Here's a minimal sample for winit-0.20.0-alpha4 that repros the issue:
https://gist.github.com/swiftcoder/740b138e00b49ee425222fe87a2efa0c

This error will also make the window **invisible** if you are rendering to it (not shown in the interests of keeping the repro case restricted to just winit).

Note that the issue does not reproduce if you use a different modifier key (i.e. `ctrl`).

### PR DESCRIPTION
**Pull request by hatoo**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

This PR fixes #1269 
On macOS, we must not change fullscreen state during fullscreen transition animation.
This PR saves target fullscreen state if `set_fullscreen` is called during fullscreen transition and call `set_fullscreen` again after fullscreen transition has end.

### CODE REVIEW

**Comment by goddessfreya** [comment]
Thank you @hatoo!

Are you familiar with cocoa and okay with reviewing this PR, @simlay?

**Comment by simlay** [comment]
I’m not super familiar with the macOS platform_impl. So if someone more familiar is around, that’d be better.

**Comment by goddessfreya** [comment]
or r? @aleksijuvani

**Comment by goddessfreya** [comment]
@aleksijuvani I imagine it would lead to an annoying array of bugs if winit just sometimes started ignoring `set_fullscreen`, no?

**Pull request merged**
