### PR TITLE
Add web examples

### PR DESCRIPTION
**Pull request by ryanisaacg**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Created or updated an example program if it would help users understand this functionality

### CODE REVIEW

**Comment by Osspial** [comment]
I ran `cargo web start --example stdweb_window --features stdweb`, but the code included in this PR doesn't seem to be enough to instantiate a webpage that contains a Winit window. Additionally, `cargo web` is giving me this message:

```
If you need to serve any extra files put them in the 'static' directory
in the root of your crate; they will be served alongside your application.
You can also put a 'stdweb_window-static' directory in your 'examples' directory.
Your application is being served at '/stdweb_window.js'. It will be automatically
rebuilt if you make any changes in your code.
```

Would it be possible to include the static files in this PR? Additionally, could we add web setup documentation to the crate's root docs?

**Comment by ryanisaacg** [comment]
@Osspial 

> I ran cargo web start --example stdweb_window --features stdweb, but the code included in this PR doesn't seem to be enough to instantiate a webpage that contains a Winit window. 

Nothing is rendered in the window, but it's there for me at least. Are you not seeing events logged / a canvas in the DOM?

We could insert some code to use webgl or HTML5 canvas to color-fill the canvas to make it obvious.

> Additionally, cargo web is giving me this message:

Cargo web will give you this message if you don't have a `static` directory. It's just a message that warns you where to put your static assets; this PR has none.

**Comment by Osspial** [comment]
@ryanisaacg ah, alright. I just checked the console log and events are indeed getting printed.

> We could insert some code to use webgl or HTML5 canvas to color-fill the canvas to make it obvious.

Would it be easier to set the page's background color, so it contrasts against the canvas' default uncleared color?

**Comment by ryanisaacg** [comment]
#1301 does this better, so I'll just make the background color change after we merge that.

**Pull request closed without merging**
