### PR TITLE
v0.30.2

### PR DESCRIPTION
**Pull request by notgull**
### Changed

- On Web, let events wake up event loop immediately when using
  `ControlFlow::Poll`.

### Fixed

- On Web, fix `EventLoopProxy::send_event()` triggering event loop immediately
  when not called from inside the event loop. Now queues a microtask instead.
- On Web, stop overwriting default cursor with `CursorIcon::Default`.
- On Web, prevent crash when using `InnerSizeWriter::request_inner_size()`.

### CODE REVIEW

**Comment by notgull** [comment]
See #3731 for the failing clippy lints

**Review by daxpedda — CHANGES_REQUESTED** [review]
The https://github.com/rust-windowing/winit/pull/3728/commits/858b84e0ce1bc0675847376e4e7910ec214a4646 commit has to be excluded, as this is is technically a breaking change.

I can do it as well tonight.

Thanks for doing this @notgull!

**Comment by kchibisov** [comment]
@daxpedda check that I've reverted the web correctly, given that there's no dedicated commit for the said _breaking_ change.

**Review by kchibisov — APPROVED** [review]

**Review by daxpedda — APPROVED** [review]
Thanks @kchibisov, Web looks good!

**Pull request merged**
