### PR TITLE
Derive more things

### PR DESCRIPTION
**Pull request by LoganDark**
Having issues where LogicalPosition<f32> has no Default.

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by LoganDark** [comment]
bruh the windows check failed because of a network error, oof

**Comment by ArturKovacs** [comment]
`Default` and `Hash` seem reasonable to derive, but `Eq` should be handled like this:
```rust
// Only implement `Eq` for `LogicalPosition`s where the inner type is `Eq`
impl<P: Eq> Eq for LogicalPosition<P> {}
```

**Comment by maroider** [comment]
Isn't that what `#[derive()]` does anyway?

**Comment by ArturKovacs** [comment]
> Isn't that what `#[derive()]` does anyway?

I clearly misunderstood the documentation. Yeah these can all just be derive.

Although please add a changelog entry along the lines of
```
- Implement `Default`, `Hash`, and `Eq` for `LogicalPosition`, `PhysicalPosition`, `LogicalSize`, and `PhysicalSize`.
```

**Comment by LoganDark** [comment]
@ArturKovacs Done

**Pull request merged**
