### PR TITLE
Implement DeviceEvent::Button on Mac

### PR DESCRIPTION
**Pull request by swiftcoder**
- [x] Tested on all platforms changed
- [x] `cargo fmt` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/tomaka/winit/blob/master/FEATURES.md), if new features were added or implemented

Addresses #955.

This should do the trick, but I don't have a solid test case handy, since my application is still on 0.19.1 (via glium/glutin), and this code has all been refactored since that version.

### CODE REVIEW

**Comment by felixrabe** [comment]
I'll give it a try later.

**Comment by felixrabe** [comment]
Ok, tested this with commit 9dd15d00d812 using your example. Seems to work as expected:

- Without your changes: DeviceEvent::Button does not get reported.
- With your changes: DeviceEvent::Button does get reported.

Didn't see any regressions, so looks fine from me.

**Comment by felixrabe** [comment]
I've [rebased against master, example commit first](/felixrabe/winit/tree/device-button-test-without-changes), so you can force-push this PR on that and all is smooth. (Yeah, I was bored and had nothing else to do.) :)

**Comment by Osspial** [comment]
Merging. Thanks for the PR!

**Pull request merged**
