### PR TITLE
Add option to enable/disable `WS_CLIPCHILDREN` window style

### PR DESCRIPTION
**Pull request by amrbashir**
While working on https://github.com/tauri-apps/wry/pull/1041 which allows adding the webview as a child window, I noticed that when setting the webview to be transparent, the portion of the parent behind it doesn't render properly and that was because of `WS_CLIPCHILDREN`

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Review by kchibisov — APPROVED** [review]

**Comment by notgull** [comment]
Why was `WS_CLIPCHILDREN` added in the first place? I'm at the gym right now so I can't do an in depth blame.

**Review by msiglreith — CHANGES_REQUESTED** [review]
This will break child rendering in non-special cases. The parent window can now overdraw the child window.

**Comment by amrbashir** [comment]
Would it make more sense to make this configurable? and what should the default behavior be?

**Comment by kchibisov** [comment]
If that will be the resolution, I'd probably suggest to put this thing on _hold_, until better days/0.30.0.

**Comment by msiglreith** [comment]
Thanks, `WS_CLIPCHILDREN` should be enabled by default.

**Comment by amrbashir** [comment]
alright, should be good to go now.

**Review by msiglreith — APPROVED** [review]

**Pull request merged**
