### PR TITLE
On Wayland, Hide CSD for fullscreen windows

### PR DESCRIPTION
**Pull request by kchibisov**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by kaimast** [comment]
Thanks for fixing this! Has this been released yet?

**Comment by kchibisov** [comment]
>Thanks for fixing this! Has this been released yet?

Yes it was in 0.22.0.

**Comment by kaimast** [comment]
Just tested this with `glutin 0.24`/`winit 0.22`.

The CSD is indeed gone but the window context is still smaller than the screen. Essentially I now have a gap at the bottom of the window that shows whatever is behind it.

Not sure if this is a glutin or winit error, but the `inner_size` of the window does not seem to get updated correctly.

**Comment by kchibisov** [comment]
@kaimast `inner_size` is delayed on update on Wayland, that's true. But if you're requesting inner_size of `X` there's no guarantee that you'll actually use it, compositor can give the size of `Y` instead. + make sure that you're properly resizing things and calling `resize` on window context.

**Comment by kchibisov** [comment]
For inner size issue look at https://github.com/rust-windowing/winit/issues/1451 , but for `resize` read through https://github.com/rust-windowing/winit/issues/1446

**Comment by kaimast** [comment]
> @kaimast `inner_size` is delayed on update on Wayland, that's true. But if you're requesting inner_size of `X` there's no guarantee that you'll actually use it, compositor can give the size of `Y` instead. + make sure that you're properly resizing things and calling `resize` on window context.

Sorry, I am actually not using inner_size but the Resize event. I am also calling window_context.resize(). 
I noticed I have the same issue with the fullscreen example in glutin. So I am pretty sure its a bug :(

**Comment by kchibisov** [comment]
please report this issue separately instead of commenting on PR. Also include some example for me to test, since I can't repro it?

**Comment by kaimast** [comment]
I did at #1509

**Pull request merged**
