### PR TITLE
Winit version 0.28.0

### PR DESCRIPTION
**Pull request by kchibisov**
## Patches that left

Some of the patches that might be worth merging for `0.28.0`:

- [x] https://github.com/rust-windowing/winit/pull/2626
- [x] ~https://github.com/rust-windowing/winit/pull/2615~ Will take more design work, so let's not block on this one
- [x] https://github.com/rust-windowing/winit/pull/2632 (web, so can't review, cc @maroider ?)
- [x] https://github.com/rust-windowing/winit/pull/2613 (not sure)
- [x] https://github.com/rust-windowing/winit/pull/2605 (bevy)
- [x] https://github.com/rust-windowing/winit/pull/2585 (awaits macOS)
- [x] https://github.com/rust-windowing/winit/pull/2576 (macOS patch about Option as Alt)
- [x] https://github.com/rust-windowing/winit/pull/2369 (fractional scaling on Wayland)
- [x] https://github.com/rust-windowing/winit/pull/2636 (required for egui)
- [x] https://github.com/rust-windowing/winit/pull/2639 (regression on master)
- [x] https://github.com/rust-windowing/winit/pull/2584

If I've missed something or you want some bug to be fixed for `v0.28.0` let me know.

Be aware that the next major release after the `0.28.0`(`0.29.0`) will contain the new Wayland backend (updated to new wayland-rs) and likely new X11 backend(mixture of Xlib + Xcb, instead of raw xlib).

--
CC of some main downstream consumers(if you're not interested in getting notified about release planning in winit let me know, so I won't even CC you again).

- `bevy`: @alice-i-cecile, @cart
- `egui`/`eframe`: @emilk
- `iced`: @hecrj
- `ggez`: @PSteinhaus
- `tauri` : @amrbashir
- `nannou`: @mitchmindtree

If you have some issues with winit that you want fixed for 0.28.0 let me know while we're in release preparation stage, so I include them and try to look into.

Also would you prefer if winit had `rc` period or you're fine with the current policy with `patch` fixes right away, given that winit don't really have breaking changes. Initially
we decided to not do `rc` releases, since it's easier to iterate and propagate the update without them, given that majority unlikely to use them and it's better to know that something broke if you push the update.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
#2605 is the most important of those for us at Bevy :)

**Comment by Wumpf** [comment]
#2636 is blocking an egui PR for maximizing windows, would love to see that in if possible (:

**Comment by MarijnS95** [comment]
@rib we have no breaking changes planned anymore for `android-activity`, right? Just making sure, otherwise we might want to push that out and update `winit` right before releasing `0.28`.

**Review by madsmtm — APPROVED** [review]
I think we should go for the new release now, all the requested changes have been made (or I've written a description on them as to why we'll delay with it).

**Comment by kchibisov** [comment]
The option as alt PR is still up, and I'll try to finish it today... The `Alt` PR should be trivial to finish anyway.

**Comment by rib** [comment]
> @rib we have no breaking changes planned anymore for `android-activity`, right? Just making sure, otherwise we might want to push that out and update `winit` right before releasing `0.28`.
> 
> (EDIT: And if not, we should do a nonbreaking patch release for the recent contributions, i.e. to reduce `logcat` spamming 🙂)

Right, no breaking changes planned currently.

Doing a release for the logging cleanup should be fine. It'll also propagate the new url for the repo.

**Comment by rib** [comment]
I had a few winit Android issues I started looking at and had wanted to make more progress with (ime + surface_size) but it's fine if those things slip to the next release.

For Android I've been looking more at issues in the JNI crate recently since I want to use it in the Android backend for Winit and but it has had a bunch of ergonomic and safety issues that I think need addressing first - so I've been a bit distracted from winit and android-activity.

**Comment by emilk** [comment]
I've tested latest `winit` with `eframe` and it seems to we working flawlessly, FWIW. I really like the new `WindowEvent::TouchpadMagnify` event ❤️

**Comment by kchibisov** [comment]
I'll schedule release for today's evening (UTC+3). If no-one has anything else to add I'd push a release.

**Comment by dhardy** [comment]
Winit `master` works with KAS; the one slight concern I note is that `EventLoopWindowTargetExtWayland` is now under `cfg(wayland_platform)` which is less easy to reproduce under downstream crates. For Winit 0.27 it's mostly copy-paste:
```rust
#[cfg(any(
    target_os = "linux",
    target_os = "dragonfly",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd"
))]
{
    use winit::platform::unix::EventLoopWindowTargetExtUnix;
    if elwt.is_wayland() {
        // Wayland-specific code here
    }
}
```
Now one needs to read the `build.rs`, but at least that has a similar `cfg` there (due to "XXX aliases are not available for the build script itself").

**Comment by kchibisov** [comment]
nah, will wait for #2665...

**Comment by MarijnS95** [comment]
@kchibisov thanks for releasing! Can you now clean up some of the branch inconsistencies? There's a `0.27` branch that points to the `0.27.1` release whereas `0.27.x` points to the latest `0.27.5` release. And the new `v0.28.x` branch has a `v` in front of it; replicate that on the other branch?

@madsmtm somehow strangely we seem to have some feature resolver problems on Rust 1.59 getting to `objc2 = "=0.3.0-beta.3"`: https://github.com/ash-rs/ash/actions/runs/4072998223/jobs/7016396013, any idea/suggestions?

**Comment by kchibisov** [comment]
@MarijnS95 msrv is 1.60 not 1.59 for the new winit.

**Comment by kchibisov** [comment]
>@kchibisov thanks for releasing! Can you now clean up some of the branch inconsistencies? There's a 0.27 branch that points to the 0.27.1 release whereas 0.27.x points to the latest 0.27.5 release. And the new v0.28.x branch has a v in front of it; replicate that on the other branch?

I'll try to look into that, but not sure if I can change much.

**Comment by madsmtm** [comment]
> @madsmtm somehow strangely we seem to have some feature resolver problems on Rust 1.59 getting to `objc2 = "=0.3.0-beta.3"`: https://github.com/ash-rs/ash/actions/runs/4072998223/jobs/7016396013, any idea/suggestions?

Simply put, `objc2`'s MSRV is `1.60`

**Pull request merged**
