### PR TITLE
Disable the maximize button on Windows if min and max dimensions equal.

### PR DESCRIPTION
**Pull request by azriel91**
This is part of the fix for https://github.com/PistonDevelopers/piston_window/issues/160

This disables the window maximize button on Windows if the min and max dimensions are both set and are equal.

 I've only tested this on Windows 10.

### CODE REVIEW

**Comment by tomaka** [comment]
I'm not sure we want to do this automatically. It's too magic.
It should probably be an option on the builder that you can trigger separately from the min/max dimensions.

**Comment by azriel91** [comment]
Okay, I'll have a look to see if adding a parameter makes sense for the Linux and Mac backends

**Comment by azriel91** [comment]
Adding a resizable `bool` flag to `WindowAttributes` appears to make sense, but the windows may not always behave as intended:

* Windows:

    Via flag support.

* OS X:

    [This blog comment](http://vgable.com/blog/2008/04/11/nswindow-setresizable/#comment-1327) indicates we can use `setStyleMask` since OS X 10.6 or later. [Rust's Tier 1 support](https://forge.rust-lang.org/platform-support.html) includes OS X 10.7 or later.

* Linux:

    - X11:

        You can use [hints](http://stackoverflow.com/questions/5557933/disable-resize-of-an-x11-window), though it's not guaranteed the backend will honour it.

    - Wayland:

        This one seems to be a rabbit hole. This [stackoverflow question](http://stackoverflow.com/questions/36671269/how-to-remove-titlebar-from-noncsd-windows-in-wayland) has a screenshot that suggests it's possible, but I don't understand Wayland enough / haven't found library docs that list how to pass flags in. Grepping [wayland-client-rs](https://github.com/vberger/wayland-client-rs) code didn't help very much.

So I'm having trouble confirming if it can be done with the Wayland backend. If someone else can pitch in it would be great. Or, we could say "this doesn't work on Wayland" though I'm not sure you want a feature that doesn't work across all variants.

**Comment by Ralith** [comment]
Wayland decorations are drawn by the client, so presumably the question is meaningless there--if you don't want a maximize button, don't draw one yourself.

**Comment by vberger** [comment]
Yes, for wayland, we should first add the ability to `wayland-window` to actually draw a "maximize" button before considering disabling it. 😅

**Comment by vberger** [comment]
@azriel91 do you plan to continue working on this PR?

**Comment by azriel91** [comment]
Woops sorry I forgot about this. I'll code something up this weekend

**Comment by azriel91** [comment]
Hiya, I've pushed a change that has a maximizable flag that the user can set to `false` to disable the maximize button on Windows, which on Windows has a side effect that also disables resizing. When trying to do the same on X11 I ran into this scenario:

* Based on [this stackoverflow answer](https://stackoverflow.com/a/5558000/1576773), the maximize button is removed when the min and max dimensions are equal
* This was observed to when I ran the min_max_size example,with the min and max dimensions equal.
* I couldn't remove the maximize button via code -- couldn't find anything on google; closest were [these docs](https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html)

I haven't got a system that runs on Wayland.

So, what should happen next?

* discard the PR (I don't mind, my use case for this has gone away)
* go with equal dimensions = non-resizable + non-maximizable
* something else

**Comment by vberger** [comment]
The recent upgrade of wayland-window should have taken care of this issue for wayland already (modulo some bug fixing in wayland-window), so you don't need to worry about it.

**Comment by francesca64** [comment]
`_NET_WM_ALLOWED_ACTIONS` could be used to disable maximization on X11, which would be trivial.

**Comment by matanui159** [comment]
Just out of curiosity what is the status of this? I need it for one of my projects. For the time being I'm just setting the max size to the base size but its not exactly the nicest solution.

**Comment by francesca64** [comment]
Someone would have to make a new PR. Windows implementation is easy, if you couldn't tell from this PR. macOS is also [quite easy](http://www.cocoabuilder.com/archive/cocoa/113682-disabling-window-zoom-button.html). X11 though... I was wrong about `_NET_WM_ALLOWED_ACTIONS`, or at the very least, it didn't work for disabling resizing. It could work for disabling maximization, but even if it does there's no guarantee a given WM will support/respect it. If that hint isn't the way to do this, then this is just flat out impossible on X11.

**Comment by matanui159** [comment]
Maybe it should be part of disabling resizable, as you mentioned here: https://github.com/tomaka/winit/pull/541#issuecomment-394093923, I've done WIN32 before and iirc it should just be a flag change. Not sure about X11, maybe check GLFW and see how it dealt with X11.

**Comment by Osspial** [comment]
Since this PR is abandoned and implemented elsewhere, I'm closing this in favor of #947.

**Pull request closed without merging**
