### PR TITLE
Add web targets to travis

### PR DESCRIPTION
**Pull request by ryanisaacg**

### CODE REVIEW

**Comment by Osspial** [comment]
Could you add lines testing this on nightly?

**Comment by ryanisaacg** [comment]
Any idea why appveyor is failing? This shouldn't be affecting it afaik

**Comment by Osspial** [comment]
@ryanisaacg Looks like it's failing to configure `gcc` properly on nightly. It's probably a configuration error somewhere on Appveyor or `rustup-init`'s side, though if it persists for a few days we should probably take a closer look at it.

**Comment by ryanisaacg** [comment]
@Osspial Are we good to merge this even with appveyor failing?

**Comment by Osspial** [comment]
@ryanisaacg yep

**Pull request merged**
