### PR TITLE
CONTRIBUTING.md: Linkify project members

### PR DESCRIPTION
**Pull request by felixrabe**

### CODE REVIEW

**Comment by ZeGentzy** [comment]
I'd merge this, but it won't let me till the tests pass :/

**Comment by ZeGentzy** [comment]
Why is this CI not done?

@Osspial think of all the trees that are dieing to this unskippable CI!

**Comment by Osspial** [comment]
@ZeGentzy Eh, trees are overrated anyway. It's not like they've done anything for us.

**Comment by Osspial** [comment]
Thinking about it, we should move that table into the wiki. That'll make it easier for people to add themselves as testers, so they don't have to go through a full PR process (which seems overblown for that purpose).

**Comment by felixrabe** [comment]
Ah, you were faster than me: https://github.com/rust-windowing/winit/wiki/Testers-and-Contributors :)

**Pull request merged**
