### PR TITLE
Add macos `with_disallow_hidpi`

### PR DESCRIPTION
**Pull request by slmjkdbtl**
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created an example program if it would help users understand this functionality

Implemented by gentz and tested myself on macOS, mimicing sdl's `SDL_WINDOW_ALLOW_HIGHDPI ` flag

### CODE REVIEW

**Comment by ZeGentzy** [comment]
@slmjkdbtl Can you resolve the merge conflict?

r? @mtak-

**Comment by ZeGentzy** [comment]
@Osspial can you just merge this? It's been a week.

**Comment by Osspial** [comment]
Sorry it took so long to respond to this!

I'm not sure I'm comfortable with exposing another platform-specific DPI override just for macOS. We've already got an [override for X11](https://docs.rs/winit/0.19.0/winit/struct.Window.html#method.get_hidpi_factor), and I don't want to keep adding platform-specific ways of controlling winit's DPI support until we have several subtly different and incompatible ways to set DPI.

There's talk going on in #796 about the HiDPI API, and I'd like to see that conclude before we decide whether or not to merge this.

**Comment by ZeGentzy** [comment]
@Osspial What's the verdict? I'd rather this gets merged.

**Comment by vberger** [comment]
Just to be sure I get a clear image, what would be the consequence of this flag precisely?

**Comment by ZeGentzy** [comment]
To quote the macos docs:
> You can opt in to high resolution by calling the method setWantsBestResolutionOpenGLSurface: when you initialize the view, and supplying YES as an argument: [..] If you don’t opt in, the system magnifies the rendered results.

Basically, if you disable this flag, the window's size on the screen will stay the same, but it's contents will get magnified. This is unlike changing the dpi, which changes the window's size.

Maybe @slmjkdbtl can provide a screenshot?

**Comment by vberger** [comment]
Ok, so This is the same as what a non-hidpi wayland app would do, so such a flag would be trivial to replicate on Wayland, and I guess it would only make sense on these platforms.

**Comment by ZeGentzy** [comment]
@slmjkdbtl Could you quickly rebase this against the new master?

**Comment by Osspial** [comment]
FWIW, I'm going to rescind my objections to this.

We could also implement this on Windows, but it would be an `EventLoop`-level flag, not a `Window`-level flag.

**Comment by ZeGentzy** [comment]
Hey, apologizes, but this PR has fallen greatly out of date. Could you rebase this against the new master and open a new PR. Anyways, I'm closing this one. Thanks.

**Pull request closed without merging**
