### PR TITLE
web: Manually emit focused event on mouse click

### PR DESCRIPTION
**Pull request by rukai**
closes https://github.com/rust-windowing/winit/issues/2112

Reasoning is explained on the issue.

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by rukai** [comment]
Resolved the merge conflict

**Review by grovesNL — APPROVED** [review]
Thank you, this seems reasonable to me!

It seems like we could also consider handling the element's `focus` event generally, but I'm not sure we could rely on the event order (e.g. `focus` might fire after `mousedown`).

**Review by maroider — APPROVED** [review]
A future refinement on this might be to avoid sending a second `Focused(true)` event when our `on_blur` handler gets run.

**Comment by rukai** [comment]
Thanks!

**Pull request merged**
