### PR TITLE
Fix Windows fullscreen toggle on windows that started invisible

### PR DESCRIPTION
**Pull request by repi**
If one created a window with `with_visibility(false)` and then done `show()` then `set_fullscreen` wasn't working properly and hid the window because the internal `WindowFlags` was still stored as `WindowFlags::VISIBLE = false`.

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by Osspial** [comment]
Thanks for the PR! Could you rebase this onto the `eventloop-2.0` branch?

**Comment by repi** [comment]
Thanks, we haven't upgraded and tested 0.20 yet but great if it has been fixed there with/after the big refactor. Can confirm later when we upgrade

**Comment by Osspial** [comment]
It looks like this particular issue has been addressed, so I'm going to close this PR. However, it looks like the test-case you describe is still showing some funky behavior which I'll look into.

**Comment by repi** [comment]
Thanks!

**Pull request closed without merging**
