### PR TITLE
On Wayland, fix coordinates in touch events when scale factor isn't 1

### PR DESCRIPTION
**Pull request by kchibisov**
- [ ] Tested on all platforms changed( don't have touch screen)
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by kchibisov** [comment]
CI failed due to some download error AFAICS.

**Comment by vberger** [comment]
LGTM overall. :+1: 

Small nitpick, I'm wondering if it may not make things clearer for whoever will read this code in the future to replace the instances of
```rust
PhysicalPosition::new(x * scale_factor, y * scale_factor)
```
with
```rust
LogicalPosition::new(x,y).to_physical(scale_factor)
```

**Comment by kchibisov** [comment]
>LogicalPosition::new(x,y).to_physical(scale_factor)

It make sense, I'll update PR.

**Comment by goddessfreya** [comment]
Merging. Thanks folks!

**Pull request merged**
