### PR TITLE
Fix panic at redraw event in non redraw phase

### PR DESCRIPTION
**Pull request by filnet**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by Kethku** [comment]
I tested this by building my app targeting your PR branch and I am still getting redraw event in non-redraw phase any time I try to move the window. I don't think this fixes the problem

**Comment by filnet** [comment]
@Kethku this PR also provides more information when the panic happens.

Could you reproduce the issue with this fix and report back the panic message ?

**Comment by Kethku** [comment]
I just pulled the resent change and the error seems to have gone away. I am trying reverting the most recent change to confirm the issue reappears.

**Comment by Kethku** [comment]
Ok it looks like on this machine I don't encounter the error which is very concerning. Remoting in to try from my other machine now.

**Comment by Kethku** [comment]
Arg. I can't get the error to reproduce in any environment anymore...

**Comment by filnet** [comment]
I had the same problem. Sometimes I can reproduce the issue 3 times in a row and sometimes it just won't reproduce. Very frustrating.

**Comment by Kethku** [comment]
Alrighty then. I can neither confirm nor deny at this moment if this PR fixes the issue

**Comment by Kethku** [comment]
I have updated my app to target this hotfix and will run with it until I find the error. I will report back in a couple of days if I have not seen it

**Comment by filnet** [comment]
This PR needs to be reviewed thoroughly. Although it seems to fix the issue, it feels like a workaround of the symptom. The root cause of the issue might still be there.

One thing, for example, it that the panic cannot be reached anymore. So why keep it ?

**Comment by tmpvar** [comment]
With this patch I was able to drag/resize a winit window (on Windows 10) and it did not panic.

I was able to consistently repro on master @ 4eddd1e5bc336e12ba06110f2ccadd64cadfd845 using the resizable example

```
     Running `target\debug\examples\resizable.exe`
Resizable: true
thread 'main' panicked at 'redraw event in non-redraw phase', src\platform_impl\windows\event_loop\runner.rs:427:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\debug\examples\resizable.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

This may not be an apples to apples comparison though as this branch is based on `0.20.0` while master is on `0.21.0`. As a test, I've rebased this branch on  4eddd1e5bc336e12ba06110f2ccadd64cadfd845 and still cannot repro the panic!

**Comment by filnet** [comment]
Superseded by https://github.com/rust-windowing/winit/pull/1461

**Pull request closed without merging**
