### PR TITLE
Show the menu bar in borderless fullscreen on macOS

### LINKED ISSUE #1195: Fullscreen Titlebar Won't Show on macOS
While in an exclusive fullscreen mode on macOS, the titlebar (while hovering over the top of the screen) doesn't slide down as expected. I've confirmed this issue with `cargo run --example window` from this repo. This issue seems to have been introduced in 5bc3cf18d98aef0a5f0a51c0cf655d37af833730 with the merge of #925.

This was originally brought to our attention in https://github.com/jwilm/alacritty/pull/2438#issuecomment-536649468.

### PR DESCRIPTION
**Pull request by irh**
Fixes #1195.

Following on from @cixel's work in #1326, this PR aims to fix the issue where the menu bar doesn't show up when using the borderless fullscreen mode on macOS.

#2046 was opened recently but following some discussion @francesca64 proposed reactivating this branch in a new PR.

There are a couple of edge cases that need to be manually tested, [e.g. this comment](https://github.com/rust-windowing/winit/pull/1326#issuecomment-761823885)
> Running `cargo run --example multithreaded`:
> 1. Press `esc` twice to close the first two windows
> 2. Press `alt`+`F`. The window goes into exclusive fullscreen
> 3. Press `F`. The window seems to change to borderless fullscreen which is indicated by the fact that I can use `cmd`+`tab` to switch between applications. But now the menu bar isn't shown.

Additionally, since I [first looked at this issue](https://github.com/rust-windowing/winit/pull/1326#issuecomment-933350528), I've added a fix for the following path:

Running `cargo run --example multithreaded`:
1. Press `F`. The window goes into borderless fullscreen.
2. Press `alt`+`F`. The window goes into exclusive fullscreen
3. Press `F`. The window returns to borderless fullscreen. At this point the menu bar should appear normal and the green 'resize' button should be active.

I assume that there are further edge cases to consider that I haven't found, the logic here is a bit thorny and it can be hard to keep track of all the options and modes, but for the main cases this seems to be working correctly, at least in my testing.

---

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by francesca64** [comment]
With the first test case, if I click somewhere else on the menu bar in borderless fullscreen, the menu bar disappears again. This only seems to happen after transitioning from exclusive->borderless, and the menu bar doesn't reappear even if I cycle exclusive->borderless again.

With the second test case, I unreliably experience a substantial delay (sometimes even briefly beach-balling) when transitioning from exclusive->borderless. However, this already happen on `master`, so it's not an issue with this PR.

**Comment by irh** [comment]
> With the first test case, if I click somewhere else on the menu bar in borderless fullscreen, the menu bar disappears again. This only seems to happen after transitioning from exclusive->borderless, and the menu bar doesn't reappear even if I cycle exclusive->borderless again.

Yes I see that too, well spotted 👍 I'll see if I can find a fix.

**Comment by irh** [comment]
OK I can see that I won't be able to find a fix any time soon (I have no clue what the root cause is, other than it likely being related to the hacks involved in exclusive fullscreen), and I'm not going to have more time to dedicate to this until sometime next week. If this needs to be fixed before merging I'd be happy for someone with more knowledge of mac windowing than me to take this over, I'm mostly just pulling on levers I don't really understand here!

**Comment by francesca64** [comment]
@irh completely understandable; windowing is a nightmare, and you've already done so much to help!

I also won't be able to investigate this until next week. If anyone wants to swoop in and try to figure this out before then, they'll be handsomely rewarded with at least 1 heart emoji.

**Comment by irh** [comment]
An update from me, I've got no spare time for at least another couple of weeks while my daughter's quarantining from a Covid close contact, so I'm not going to be able to help with pushing this forward for quite a while.

I've also noticed that the multithreaded example is badly broken on the M1 macbook that I use at home (the wrong resolution is used in exclusive fullscreen, and interaction seems broken).

My thinking is that the thing to do here would be to merge a fix for the missing menu issue so that at least the idiomatic macOS fullscreen mode is working correctly, and then leave the refinement of mode switching as followup work? I fear that getting the mode switching to 100% will be a bit of a thorny challenge that will continue to drag on, and the fix for the primary issue is pretty straightforward, so it seems reasonable to me to treat the two topics separately.

**Review by madsmtm — APPROVED** [review]
Agree, I even think we should just merge this as-is since it includes helpful considerations and goes part of the way in fixing the mode-switching issue.

I've opened https://github.com/rust-windowing/winit/issues/2068 to track fixing the mode-switching for later.

**Review by francesca64 — APPROVED** [review]
@madsmtm seconded; this PR is strictly an improvement.

@irh thank you for everything you've done, and I wish you and your family the best!

**Pull request merged**
