### PR TITLE
Merge master into new-keyboard

### PR DESCRIPTION
**Pull request by ArturKovacs**
Merges the `master` branch into the `new-keyboard` branch. I'm doing this because I want to fix the android build but there was a new addition to handle some key-presses on android since the `new-keyboard` branch was created.

I don't understand why github shows every commit on the `new-keyboard` branch when this PR only adds the new ones from the `master`. @msiglreith would you mind looking at this so this can be merged?

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Review by msiglreith — APPROVED** [review]
LGTM, was a bit confused as it's not the current master

**Comment by ArturKovacs** [comment]
Apparently I don't know how to use git. Forgot to pull from upstream before merging. Also the build is failing with this weird allocation failure in rustup. 😕

**Comment by ArturKovacs** [comment]
Ooh no... I wanted to create a new PR where the merge commit is on top of the squashed commit. But I did this on a new branch I created locally, which was set to track winit's `new-keyboard` and I accidentally pushed directly to winit instead of my own fork. This is embarrassing. The changes should be alright, but @msiglreith could you check if the thing I pushed to `new-keyboard` is not completely stupid.

In the meantime I'm closing this

**Comment by msiglreith** [comment]
looks fine to me 👍

**Pull request closed without merging**
