### PR TITLE
Remove entries from PULL_REQUEST_TEMPLATE.md that are now covered by CI

### PR DESCRIPTION
**Pull request by rukai**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

The more entries there are, the more likely people are to start just ignoring them all.
By removing the ones already covered by CI then the remaining entries are more likely to be followed.

### CODE REVIEW

**Review by madsmtm — APPROVED** [review]
Agree, had this on the TODO-list as well, thanks!

**Comment by rukai** [comment]
I'm not sure why the builds arent running.
I tried force pushing to trigger it but that didnt work.
Maybe github has some kind of security feature blocking it since I touched `.github/`?

**Comment by maroider** [comment]
> I'm not sure why the builds arent running.

Our CI config makes GitHub confused. See #2130.

**Comment by maroider** [comment]
Since #2130 has been merged, CI ought to run once you force-push again. If that doesn't work, then you may need to rebase onto `master`.

**Comment by madsmtm** [comment]
Nice, thanks!

**Pull request merged**
